'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const enabled=!!process.env.GP_CORE_MIGRATOR_URL;
test('Trade blocks 2-5 use native PostgreSQL worker reads, paired inventory snapshots and durable suggestions',{skip:!enabled},async()=>{
 await require('../test-support/postgresql-migration/report-fixture').withReportFixture(async f=>{
  await f.core.migrator.query('SET ROLE gp_core_owner');await f.core.migrator.query("INSERT INTO gp.cost_centers(id,code,name,type,cost_center_type_id) VALUES('cc19','19','Synthetic 19','branch','branch'); INSERT INTO gp.locations(id,name,active,cost_center_id) VALUES('19','Synthetic 19',1,'cc19')");await f.core.migrator.query('RESET ROLE');
  const source=await require('../test-support/trade-insights-fixture').insightFixture({access:f.access,protection:f.protection,scopeId:'synthetic-migration',ownerId:'00001'});
  const runtime=require('../lib/persistence/repositories/trade-insights').createTradeInsightRuntime(f.runtimeOptions),run=(kind,input={})=>runtime.run(()=>f.resolvePrincipal('00001'),kind,input),worker=(kind,query={})=>f.worker.run({operation:'trade-insights',kind,query,session:{employeeNumber:'00001'}}),session=await f.resolvePrincipal('00001');
  await require('../test-support/trade-suggestions-fixture').seedSuggestions({...source,scopeId:'synthetic-migration',app:{provider:f.access},vault:f.vault,protection:f.protection,state:{session},run},{snapshotAt:'2026-09-12T09:00:00.000Z'});
  await source.ingest('ARTIKEL_STAMMGelöscht',[{EAN:'OLD-42',Artikelbezeichnung:'Native archive',Anlagedatum:'2010-01-01T00:00:00.000',Löschdatum:'2026-09-11T00:00:00.000'}],{sourceInstance:'tradefoto-weum'});
  const inventory=await require('../test-support/trade-stocktakes-fixture').seedStocktakes(source,{snapshotAt:'2026-09-12T09:00:00.000Z'});
  assert.equal((await worker('article-history',{query:'OLD-42',searchMode:'exact'})).rows[0].status,'archived');
  await source.ingest('WE',[{We_ID:'99',We:false,Umlagerung:true,EAN:'000042',FilialID:'19',Filialid2:'18',Menge:'-2',WEDatum:'2026-09-10T00:00:00.000',KorbId:1}],{sourceInstance:'tradefoto-weum'});
  const movement=(await worker('movements',{dateFrom:'2026-09-01'})).rows[0];assert.equal(movement.quantity,'-2');assert.equal(movement.references.basket.status,'matched');
  const overview=await worker('stocktakes'),head=overview.rows.find(r=>r.sourceLocation==='18'),q={stocktakeId:head.id,stocktakeVersion:String(head.revision),stocktakeSource:head.sourceHash};assert.equal(head.positions,120);const detail=await worker('stocktakes',q);assert.equal(detail.rows.length,4);assert.equal(detail.rows.find(r=>r.articleNumber==='OLD-42').articleReference.status,'archived');
  const exact=await worker('suggestions',{articleNumber:'000042'});assert.equal(exact.scanned,2);assert.equal(exact.rows.length,2);
  const suggestions=await worker('suggestions');assert.equal(suggestions.rows.find(r=>r.articleNumber==='000042'&&r.sourceLocation==='18').type,'transfer');assert.ok(suggestions.rows.every(r=>r.availableTransferQuantity===null));
  const queue=require('../lib/persistence/repositories/trade-insight-jobs').createTradeInsightJobs({access:f.access,vault:f.vault,runtime,resolvePrincipal:f.resolvePrincipal,dispatchRead:input=>f.worker.run(input),scopeId:'synthetic-migration'});
  try{const job=await queue.create(session,{kind:'stocktakes',query:q,title:'Native Inventurdifferenzen'});await queue.tick();const saved=await queue.get(session,job.id);assert.equal(saved.result.rows.length,4);
   const next={...inventory.options,fileSha256:'c'.repeat(64),snapshotAt:'2026-09-13T09:00:00.000Z'};await source.ingest('Inventur',inventory.heads,next);await assert.rejects(worker('stocktakes'),e=>e.code==='IMPORT_BESTELL_SOURCE_INCOMPLETE');await source.ingest('Inventurdetails',inventory.details,next);assert.equal((await worker('stocktakes')).rows.length,2);await assert.rejects(worker('stocktakes',q),e=>e.code==='IMPORT_HISTORY_ANALYSIS_CHANGED');assert.deepEqual((await queue.get(session,job.id)).result,saved.result);
  }finally{await queue.stop();}
  console.log(JSON.stringify({qualification:'trade-blocks-2-through-5-native',articleHistory:true,movements:true,stocktakes:true,suggestions:true,sourceReplacement:true,savedSnapshot:true}));
 });
});
test('Six-block views run against native Core/Sales, preserve GP annotations and enforce worker authority', {skip:!enabled},async()=>{
 await require('../test-support/postgresql-migration/report-fixture').withReportFixture(async f=>{
  const migration=require('../lib/persistence/postgresql/core/trade-annotations');
  assert.equal(Number((await f.core.migrator.query('SELECT count(*) AS n FROM gp.trade_annotations')).rows[0].n),0);
  await f.core.migrator.query('SET ROLE gp_core_owner');await f.core.migrator.query('DROP TABLE gp.trade_annotations,gp.trade_annotations_migration_history');await f.core.migrator.query('RESET ROLE');
  const fault=Object.assign(new Error('Synthetic migration interruption'),{code:'SYNTHETIC_MIGRATION_STOP'});
  await assert.rejects(migration.migrate({query:(sql,...args)=>sql.startsWith('GRANT SELECT,INSERT')?Promise.reject(fault):f.core.migrator.query(sql,...args)}),e=>e===fault);
  assert.equal((await f.core.migrator.query("SELECT to_regclass('gp.trade_annotations') AS name")).rows[0].name,null);
  const applied=await migration.migrate(f.core.migrator);assert.equal((await migration.migrate(f.core.migrator)).applied,false);
  assert.equal((await f.core.migrator.query("SELECT has_table_privilege('gp_core_app','gp.trade_annotations_migration_history','UPDATE') AS write")).rows[0].write,false);
  await f.core.migrator.query('SET ROLE gp_core_owner');await f.core.migrator.query("INSERT INTO gp.cost_centers(id,code,name,type,cost_center_type_id) VALUES('cc19','19','Synthetic 19','branch','branch'); INSERT INTO gp.locations(id,name,active,cost_center_id) VALUES('19','Synthetic 19',1,'cc19')");await f.core.migrator.query('RESET ROLE');
  const source=await require('../test-support/trade-insights-fixture').insightFixture({access:f.access,protection:f.protection,scopeId:'synthetic-migration',ownerId:'00001',branches:['18','19']});
  const filialMaster=(await source.masters.mappings({table:'FILIALEN',sourceInstance:'tradefoto-trade',key:'18'})).items[0];
  const holds=await f.access.queryOne(require('../lib/persistence/statements/import-master-data').IMPORT_MASTER_STATEMENTS.holdCount,{recordId:filialMaster.id});assert.ok(holds.count>0);
  const storedBinding=await f.access.queryOne(require('../lib/persistence/statements/import-master-data').IMPORT_MASTER_STATEMENTS.getBinding,{recordId:filialMaster.id});
  await assert.rejects(source.masters.undo(storedBinding.lastEventId),e=>e.code==='IMPORT_UNDO_DEPENDENCIES');
  await assert.rejects(f.access.transaction(tx=>tx.execute(require('../lib/persistence/statements/import-master-data').IMPORT_MASTER_STATEMENTS.insertHold,{recordId:filialMaster.id,consumerId:'history.00000000-0000-0000-0000-000000000000.1'})),e=>e.code==='PERSISTENCE_UNKNOWN');
  assert.equal(Number((await f.core.migrator.query('SELECT count(*) AS n FROM gp.import_master_holds')).rows[0].n),0);
  await source.ingest('ARTIKEL_Warengruppen',[{Warengruppe:1,Bezeichnung:'Synthetic goods'}],{master:true});
  await source.ingest('ARTIKEL_Sortimente',[{Sortiment:10,Warengruppe:1,Bezeichnung:'Synthetic cameras'}],{master:true});
  await source.ingest('ARTIKEL_STAMM',[{EAN:'000042',Artikelbezeichnung:'Native synthetic camera',Sortiment:10,DurchschnittEK:'100',Sachkonto:false,OhneBestand:false}],{master:true});
  await source.ingest('ARTIKEL_FILIALEN',[{EAN:'000042',FilialID:18,FBestand:'2'}],{sourceInstance:'tradefoto-trade'});
  await source.ingest('Reparatur',[{ReparaturNr:1,FilialId:'18',KUND_NR:42,AName:'Native synthetic camera',ANr:'NATIVE-42',erledigt:true,Anlegedatum:'2026-08-01T10:00:00.000'}]);
  const runtime=require('../lib/persistence/repositories/trade-insights').createTradeInsightRuntime({...f.runtimeOptions,today:()=> '2026-09-14'}),run=(kind,query={})=>runtime.run(()=>f.resolvePrincipal('00001'),kind,query);
  const worker=(kind,query={})=>f.worker.run({operation:'trade-insights',kind,query,session:{employeeNumber:'00001'}});
  let page=await worker('purchasing');assert.equal(page.rows.length,50);page=await worker('purchasing',{cursor:page.next});assert.equal(page.rows.length,15);
  const {createTradeInsightJobs}=require('../lib/persistence/repositories/trade-insight-jobs');
  const session=await f.resolvePrincipal('00001');let queueTime=Date.now();
  const makeInsightQueue=()=>createTradeInsightJobs({access:f.access,vault:f.vault,runtime,resolvePrincipal:f.resolvePrincipal,dispatchRead:input=>f.worker.run(input),scopeId:'synthetic-migration',now:()=>queueTime});
  const firstQueue=makeInsightQueue();let resumedQueue;
  try {
   const job=await firstQueue.create(session,{kind:'purchasing',query:{},title:'Native Ergebnisablage'});
   await firstQueue.tick();assert.equal((await firstQueue.list(session))[0].processed,50);await firstQueue.stop();
   queueTime+=180001;resumedQueue=makeInsightQueue();await resumedQueue.tick();
   const saved=await resumedQueue.get(session,job.id);assert.equal(saved.status,'completed');assert.equal(saved.result.rows.length,65);
   assert.equal(new Set(saved.result.rows.map(row=>row.id)).size,65);
   const payload=(await f.access.queryOne(require('../lib/persistence/statements/sales-report-jobs').SALES_REPORT_JOB_STATEMENTS.get,{scope:'synthetic-migration:trade-insights',id:job.id})).payload;
   assert.doesNotMatch(payload,/Native Ergebnisablage|articleNumber/);
   await resumedQueue.rename(session,job.id,{title:'Gespeicherter Stand'});
   assert.deepEqual((await resumedQueue.get(session,job.id)).result,saved.result);
   await resumedQueue.remove(session,job.id);assert.equal((await resumedQueue.list(session)).length,0);
  } finally {await firstQueue.stop();await resumedQueue?.stop();}
  const context=await worker('context');assert.equal(context.projection.classify,true);assert.equal(context.projection.repairWrite,true);
  await run('classification-save',{level:'wgr',key:'1',kind:'goods',expectedRevision:0});
  let inventory=await worker('inventory');assert.equal(inventory.rows[0].classification.kind,'goods');assert.equal(inventory.rows[0].stockValue,'200');
  await require('../test-support/trade-insights-cash').insightCashFixture({app:{provider:f.access},protection:f.protection,vault:f.vault,state:{session:await f.resolvePrincipal('00001')}},{scopeId:'synthetic-migration',ownerId:'00001',count:230,customer:'31'});
  let prices=await worker('prices',{query:'000042',dateFrom:'2026-06-01',dateTo:'2026-09-01'});assert.ok(prices.next);assert.equal(prices.rows.length,0);
  prices=await worker('prices',{query:'000042',dateFrom:'2026-06-01',dateTo:'2026-09-01',cursor:prices.next});assert.equal(prices.next,null);assert.equal(prices.rows.length,2);assert.equal(prices.rows.find(r=>r.locationId==='18').average,'120');
  const customer=await worker('customer-history',{customer:'31'});assert.equal(customer.rows.length,25);assert.ok(customer.rows.every(r=>r.kind==='cash'));
  const stockQuery={query:'000042',dateFrom:'2026-06-01',dateTo:'2026-09-01'};
  let stock=await worker('inventory',stockQuery);assert.ok(stock.next);assert.equal(stock.rows.length,0);
  stock=await worker('inventory',{...stockQuery,cursor:stock.next});assert.equal(stock.next,null);assert.equal(stock.rows[0].soldNet,'455');
  const repair=(await worker('repairs')).rows[0];assert.equal(repair.sourceStatus,'ready');assert.equal(repair.gpStatus,'unassigned');
  await run('repair-save',{id:repair.id,state:'collected',expectedRevision:0});assert.equal((await worker('repair-detail',{id:repair.id})).gpStatus,'collected');
  await assert.rejects(run('repair-save',{id:repair.id,state:'ready',expectedRevision:0}),e=>e.status===409);
  await source.ingest('Reparatur',[{ReparaturNr:2,FilialId:'18',KUND_NR:42,AName:'Another case',erledigt:false}],{snapshotAt:'2026-09-14T10:00:00.000Z'});
  assert.equal((await worker('repair-detail',{id:repair.id})).gpStatus,'collected');
  await f.core.migrator.query('SET ROLE gp_core_owner');await f.core.migrator.query("UPDATE gp.portal_users SET active=0 WHERE employee_number='00001'");await f.core.migrator.query('RESET ROLE');
  await assert.rejects(worker('repairs'),e=>e.code==='IMPORT_FORBIDDEN');
  await f.core.migrator.query('SET ROLE gp_core_owner');await f.core.migrator.query("UPDATE gp.portal_users SET active=1 WHERE employee_number='00001'");await f.core.migrator.query('RESET ROLE');
  assert.equal((await worker('repairs')).rows.length,2);
  console.log(JSON.stringify({qualification:'six-block-native',migrationApplied:applied.applied,purchasing:true,classification:true,repairs:true,revocation:true}));
 });
});
