"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { PRIVACY_ORGANIZATION_CATALOG: catalog, createPrivacyLedger, verifyPrivacyLedger, applyPrivacyCommand, projectPrivacyLedger, PrivacyOrganizationError } = require("../lib/privacy-organization");
const { canonicalSha256 } = require("../lib/work-rules/receipt");
const NOW = "2026-10-03T08:00:00.000Z";
const author = { employeeNumber: "SYNTHETIC-A", role: "hr", personal: true, permissions: ["privacy_organization:manage", "privacy_organization:approve"] };
const reviewer = { ...author, employeeNumber: "SYNTHETIC-B" };
function command(ledger, input, actor = author, now = NOW) { return applyPrivacyCommand(ledger, { ...input, expectedRevision: ledger.revision }, { actor, now }); }
function expectCode(fn, code) { assert.throws(fn, (error) => error instanceof PrivacyOrganizationError && error.code === code); }
function projection(ledger, now = NOW, id) { const result = projectPrivacyLedger(ledger, { now }); return id ? result.records.find((record) => record.id === id) : result; }
function create(ledger, kind, payload, id = kind, now = NOW) { return command(ledger, { action: "create", kind, id, payload }, author, now); }
function approve(ledger, id, now = NOW) { ledger = command(ledger, { action: "submit", id }, author, now); return command(ledger, { action: "approve", id, decision: { reason: "Unabhängige synthetische Fachprüfung", evidenceReference: "QA-REVIEW" } }, reviewer, now); }
const ORG = { controllerName: "Synthetische Testorganisation", controllerContact: "Fiktiver Organisationskontakt", controllerRole: "controller", dpoName: "Synthetische Fachperson", dpoContact: "Fiktiver Fachkontakt", worksCouncil: "absent", privacyOwnerEmployeeNumber: author.employeeNumber, responseContact: "Fiktive Vorfallkontaktstelle", reviewOn: "2027-12-31" };
const ACTIVITY = { title: "Synthetischer Testprozess", ownerEmployeeNumber: author.employeeNumber, purpose: "Testzweck", systemScope: "Synthetisches isoliertes System", dataSubjects: "Beschäftigte als Kategorie", dataCategories: "Kontokennungen als Kategorie", recipients: "Keine externen Empfänger", processors: "Keine in diesem synthetischen Fall", storageLocations: "Fiktive lokale Testumgebung", transfers: "none", retention: "Fiktive begründete Testfrist", toms: "Synthetische Zugriffskontrolle", legalBasis: "Fiktive Fachprüfung", specialCategories: "no", reviewOn: "2027-12-31" };
const BREACH = { title: "Synthetischer Vorfall", ownerEmployeeNumber: author.employeeNumber, roleInIncident: "controller", discoveredAt: "2026-10-02T07:30:00Z", controllerAwareAt: "2026-10-02T08:00:00Z", breachConfirmed: "yes", classificationReason: "Synthetischer kontrollierter Test", breachTypes: ["confidentiality"], dataCategories: "Kontokennungen", affectedGroups: "Beschäftigte als Kategorie", consequences: "Fiktiver kontrollierter Sachverhalt", containment: "Isolierte Testdaten", remediation: "Synthetische Abhilfe", riskAssessment: "Synthetische Einzelfallprüfung", risk: "risk", authorityDecision: "notify", subjectDecision: "not_required", subjectReason: "Synthetisch kein hohes Risiko", contact: "Fiktive Anlaufstelle", followUpStatus: "none_needed", followUpReason: "Synthetisch vollständig dokumentiert", remediationComplete: true };
function orgLedger() { return approve(command(createPrivacyLedger(), { action: "update", id: "organization", payload: ORG }), "organization"); }
function activityLedger() { return approve(create(orgLedger(), "activity", ACTIVITY), "activity"); }
function dpiaPayload(ledger, extra = {}) { return { title: "Synthetische DSFA-Prüfung", activityId: "activity", activitySha256: ledger.records.find((record) => record.id === "activity").contentSha256, screening: "not_required", screeningReasons: "Dokumentierte synthetische Einzelfallprüfung aller relevanten Kriterien", screeningSourceRefs: ["gdpr-2016-679", "at-dsfa-v", "at-dsfa-av"], dpoAdvice: "Synthetische dokumentierte Beratung", reviewOn: "2027-12-31", ...extra }; }
function agreementPayload(ledger, extra = {}) { return { title: "Synthetische Kontrollmaßnahme", activityId: "activity", activitySha256: ledger.records.find((record) => record.id === "activity").contentSha256, scope: "Synthetischer Geltungsbereich", worksCouncil: "absent", assessment: "avrag10", assessmentReason: "Synthetische arbeitsrechtliche Einzelfallprüfung", gdprBasis: "Gesonderte synthetische Datenschutzprüfung", agreementStatus: "effective", legalInstrument: "individual_consents", instrumentReference: "SYNTHETIC-INSTRUMENT", validFrom: "2026-01-01", signatoriesConfirmed: true, consentCoverage: "documented_complete", consentEvidenceReference: "SYNTHETIC-COVERAGE", withdrawalProcess: "Fiktiver Kündigungs- und Abdeckungsprozess", reviewOn: "2027-12-31", ...extra }; }

test("genesis contains only one neutral draft and caller-injected known facts", () => {
  const ledger = createPrivacyLedger(); assert.equal(ledger.revision, 0); assert.equal(ledger.records.length, 1); assert.equal(ledger.records[0].payload.dpoName, ""); assert.equal(ledger.records[0].payload.worksCouncil, "unknown"); assert.equal(ledger.records[0].status, "draft"); assert.equal(verifyPrivacyLedger(ledger).valid, true);
  const seeded = createPrivacyLedger({ initialOrganization: { dpoName: "Synthetische externe Person", worksCouncil: "absent" } }); assert.equal(seeded.records[0].payload.dpoEmployeeNumber, ""); assert.notEqual(seeded.receiptSha256, ledger.receiptSha256); assert.equal(seeded.events.length, 0);
});
test("catalog is immutable; templates are unconfirmed metadata, never approved records", () => {
  assert.equal(Object.isFrozen(catalog), true); assert.equal(catalog.activityTemplates.length, 12); for (const template of catalog.activityTemplates) { assert.equal(template.factsStatus, "unconfirmed"); assert.equal(template.kind, "activity"); assert.equal(Object.hasOwn(template, "approvedBy"), false); }
  for (const source of catalog.sources) { assert.match(source.url, /^https:\/\//); assert.match(source.ownSummarySha256, /^[a-f0-9]{64}$/); assert.equal(source.hashKind, "application_summary_not_external_document"); const { ownSummarySha256, hashKind, ...ownSummary } = source; assert.equal(canonicalSha256(ownSummary), ownSummarySha256); }
});
test("draft write leaves input unchanged and adds immutable actor/time/hash evidence", () => {
  const before = createPrivacyLedger(); const copy = JSON.stringify(before); const next = create(before, "activity", { title: "Test" }); assert.equal(JSON.stringify(before), copy); assert.equal(next.revision, 1); assert.equal(next.events[0].actor.employeeNumber, author.employeeNumber); assert.equal(next.events[0].at, NOW); assert.equal(next.events[0].recordId, "activity"); assert.equal(verifyPrivacyLedger(next).valid, true);
});
test("global revision detects stale writes without changing existing state", () => {
  const ledger = create(createPrivacyLedger(), "activity", { title: "Test" }); expectCode(() => applyPrivacyCommand(ledger, { action: "update", id: "organization", payload: {}, expectedRevision: 0 }, { actor: author, now: NOW }), "STALE_REVISION");
});
for (const [label, actor] of [["nonpersonal", { ...author, personal: false }], ["permission absent", { ...author, permissions: [] }], ["developer", { ...author, role: "developer" }], ["system", { ...author, role: "system" }], ["missing principal", { ...author, employeeNumber: "" }], ["empty role", { ...author, role: "" }]]) test(`trusted personal authorization: ${label}`, () => { expectCode(() => command(createPrivacyLedger(), { action: "update", id: "organization", payload: {} }, actor), "FORBIDDEN"); });
for (const [key, value, code] of [["rawPeople", ["Synthetic"], "UNKNOWN_FIELD"], ["transfers", "probably_none", "INVALID_FIELD"], ["sourceRefs", "reference", "INVALID_FIELD"], ["title", "x".repeat(241), "INVALID_FIELD"], ["reviewOn", "2026-02-30", "INVALID_DATE"], ["reviewOn", "0000-01-01", "INVALID_DATE"]]) test(`strict activity payload: ${key} ${code}`, () => { expectCode(() => create(createPrivacyLedger(), "activity", { [key]: value }), code); });
test("null payload, accessors and non-JSON data are rejected", () => {
  expectCode(() => create(createPrivacyLedger(), "activity", null), "INVALID_OBJECT"); const accessor = {}; Object.defineProperty(accessor, "title", { enumerable: true, get() { throw new Error("must not execute"); } }); expectCode(() => create(createPrivacyLedger(), "activity", accessor), "INVALID_OBJECT"); expectCode(() => createPrivacyLedger({ initialOrganization: { notes: () => "no" } }), "INVALID_FIELD");
});
test("unknown organization fields and duplicate organization/record IDs rejected", () => { expectCode(() => createPrivacyLedger({ initialOrganization: { name: "No alias" } }), "UNKNOWN_FIELD"); expectCode(() => create(createPrivacyLedger(), "organization", {}), "INVALID_ACTION"); const ledger = create(createPrivacyLedger(), "activity", {}); expectCode(() => create(ledger, "activity", {}), "INVALID_ID"); });
test("unknown or incomplete VVT cannot submit and does not infer exemption", () => { const ledger = create(createPrivacyLedger(), "activity", { title: "Personalverwaltung" }); const record = projection(ledger, NOW, "activity"); assert.equal(record.readiness.ready, false); assert.equal(record.payload.transfers, "unknown"); assert.equal(record.payload.specialCategories, "unknown"); expectCode(() => command(ledger, { action: "submit", id: "activity" }), "REVIEW_INCOMPLETE"); });
test("organization requires contact even when named DPO has no GP account", () => { const ledger = command(createPrivacyLedger(), { action: "update", id: "organization", payload: { ...ORG, dpoContact: "" } }); assert.ok(projection(ledger, NOW, "organization").readiness.issues.some((issue) => issue.code === "DPO_CONTACT_MISSING")); const ready = orgLedger(); assert.equal(projection(ready, NOW, "organization").readiness.releaseReady, true); assert.ok(projection(ready, NOW, "organization").readiness.warnings.some((issue) => issue.code === "DPO_NO_GP_ACCOUNT")); });
test("approval requires other personal principal and explicit approve permission", () => { const ledger = command(command(createPrivacyLedger(), { action: "update", id: "organization", payload: ORG }), { action: "submit", id: "organization" }); expectCode(() => command(ledger, { action: "approve", id: "organization", decision: { reason: "Synthetic" } }), "SELF_APPROVAL"); expectCode(() => command(ledger, { action: "approve", id: "organization", decision: { reason: "Synthetic" } }, { ...reviewer, permissions: ["privacy_organization:manage"] }), "FORBIDDEN"); });
test("submitter cannot approve another author's draft", () => { let ledger = command(createPrivacyLedger(), { action: "update", id: "organization", payload: ORG }); ledger = command(ledger, { action: "submit", id: "organization" }, reviewer); expectCode(() => command(ledger, { action: "approve", id: "organization", decision: { reason: "Synthetic" } }, reviewer), "SELF_APPROVAL"); });
test("every draft edit withdraws approval while preserving the approved snapshot", () => { const ledger = orgLedger(); const old = ledger.records[0].history.at(-1); const next = command(ledger, { action: "update", id: "organization", payload: { notes: "Changed basis" } }); assert.equal(next.records[0].approvedBy, ""); assert.equal(next.records[0].status, "draft"); assert.deepEqual(next.records[0].history.at(-2), old); assert.equal(projection(next).summary.releaseReady, false); });
test("return keeps evidence and requires re-submission before independent approval", () => { let ledger = command(command(createPrivacyLedger(), { action: "update", id: "organization", payload: ORG }), { action: "submit", id: "organization" }); ledger = command(ledger, { action: "return", id: "organization", decision: { reason: "Please document basis" } }, reviewer); assert.equal(ledger.records[0].status, "returned"); expectCode(() => command(ledger, { action: "approve", id: "organization", decision: { reason: "Synthetic" } }, reviewer), "INVALID_STATE"); });
test("VVT transfer and special-category safeguards cannot be skipped", () => { let ledger = create(orgLedger(), "activity", { ...ACTIVITY, transfers: "documented", specialCategories: "yes" }); assert.deepEqual(projection(ledger, NOW, "activity").readiness.issues.map((entry) => entry.code), ["TRANSFER_DETAILS_MISSING", "SPECIAL_BASIS_MISSING"]); ledger = command(ledger, { action: "update", id: "activity", payload: { transferDetails: "Synthetischer Transferbeleg", specialLegalBasis: "Synthetische zusätzliche Voraussetzung" } }); assert.equal(projection(ledger, NOW, "activity").readiness.ready, true); });
test("organization review dates are evaluated in Europe/Vienna at midnight", () => { let ledger = orgLedger(); ledger = command(ledger, { action: "update", id: "organization", payload: { reviewOn: "2026-10-03" } }); ledger = approve(ledger, "organization"); assert.equal(projection(ledger, "2026-10-03T21:59:59Z", "organization").readiness.ready, true); assert.equal(projection(ledger, "2026-10-03T22:00:00Z", "organization").readiness.ready, false); });
test("expired organization blocks otherwise complete VVT approval", () => { let ledger = orgLedger(); ledger = command(ledger, { action: "update", id: "organization", payload: { reviewOn: "2026-10-03" } }); ledger = approve(ledger, "organization"); ledger = create(ledger, "activity", ACTIVITY); assert.ok(projection(ledger, "2026-10-04T08:00:00Z", "activity").readiness.issues.some((entry) => entry.code === "ORGANIZATION_NOT_APPROVED")); });
test("DPIA non-requirement needs exact approved VVT, reasoning, sources and DPO advice", () => { let ledger = activityLedger(); const payload = dpiaPayload(ledger); ledger = create(ledger, "dpia", payload); ledger = approve(ledger, "dpia"); assert.equal(projection(ledger, NOW, "dpia").readiness.releaseReady, true); const incomplete = create(activityLedger(), "dpia", { ...payload, screeningReasons: "", screeningSourceRefs: [], dpoAdvice: "" }); assert.equal(projection(incomplete, NOW, "dpia").readiness.ready, false); });
test("changed VVT invalidates already approved DPIA and agreement projections", () => { let ledger = activityLedger(); ledger = approve(create(ledger, "dpia", dpiaPayload(ledger)), "dpia"); ledger = approve(create(ledger, "works_agreement", agreementPayload(ledger)), "works_agreement"); ledger = command(ledger, { action: "update", id: "activity", payload: { purpose: "Changed purpose" } }); for (const id of ["dpia", "works_agreement"]) { const record = projection(ledger, NOW, id); assert.equal(record.readiness.releaseReady, false); assert.ok(record.readiness.issues.some((entry) => entry.code === "STALE_VVT")); assert.equal(record.status, "approved"); } });
test("DPIA mismatched hash or unsupported source gives no green outcome", () => { let ledger = activityLedger(); ledger = create(ledger, "dpia", dpiaPayload(ledger, { activitySha256: "a".repeat(64), screeningSourceRefs: ["UNVERIFIED"] })); const issues = projection(ledger, NOW, "dpia").readiness.issues; assert.ok(issues.some((entry) => entry.code === "STALE_VVT")); assert.ok(issues.some((entry) => entry.code === "SCREENING_SOURCES_MISSING")); });
const REQUIRED_DPIA = { screening: "required", assessmentSummary: "Synthetische Beschreibung", necessity: "Synthetische Abwägung", risks: "Synthetische Risiken", mitigations: "Synthetische Maßnahmen", residualRisk: "high", consultation: "pending" };
test("high residual risk cannot bypass prior consultation or its conditions", () => { let ledger = activityLedger(); ledger = create(ledger, "dpia", dpiaPayload(ledger, REQUIRED_DPIA)); expectCode(() => command(ledger, { action: "submit", id: "dpia" }), "REVIEW_INCOMPLETE"); ledger = command(ledger, { action: "update", id: "dpia", payload: { consultation: "completed", consultationReference: "SYNTHETIC-CONSULTATION", consultationOutcome: "blocked" } }); assert.equal(projection(ledger, NOW, "dpia").readiness.ready, false); ledger = command(ledger, { action: "update", id: "dpia", payload: { consultationOutcome: "conditions_satisfied" } }); assert.equal(projection(ledger, NOW, "dpia").readiness.ready, true); });
test("non-required DPIA does not coexist with recorded high residual risk", () => { let ledger = activityLedger(); ledger = create(ledger, "dpia", dpiaPayload(ledger, { residualRisk: "high" })); assert.ok(projection(ledger, NOW, "dpia").readiness.issues.some((entry) => entry.code === "SCREENING_CONTRADICTION")); });
test("required DPIA low risk needs reason for no consultation", () => { let ledger = activityLedger(); ledger = create(ledger, "dpia", dpiaPayload(ledger, { ...REQUIRED_DPIA, residualRisk: "low", consultation: "not_required" })); assert.equal(projection(ledger, NOW, "dpia").readiness.ready, false); ledger = command(ledger, { action: "update", id: "dpia", payload: { consultationReference: "Synthetisch risikobezogen begründet" } }); assert.equal(projection(ledger, NOW, "dpia").readiness.ready, true); });
for (const [label, aware, expected] of [["weekend", "2026-10-02T10:00:00+02:00", "2026-10-05T08:00:00.000Z"], ["spring DST", "2026-03-28T12:00:00+01:00", "2026-03-31T11:00:00.000Z"], ["autumn DST", "2026-10-24T12:00:00+02:00", "2026-10-27T10:00:00.000Z"]]) test(`breach clock is 72 absolute hours: ${label}`, () => { const now = new Date(Date.parse(aware) + 1000).toISOString(); const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, controllerAwareAt: aware, discoveredAt: aware }, "breach", now); assert.equal(projection(ledger, now, "breach").deadlines.authorityDueAt, expected); });
test("72-hour boundary states are exact and include unknown risk", () => { const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, risk: "unknown", authorityDecision: "unknown" }); assert.equal(projection(ledger, "2026-10-05T07:59:59.999Z", "breach").deadlines.authorityState, "pending"); assert.equal(projection(ledger, "2026-10-05T08:00:00.000Z", "breach").deadlines.authorityState, "due"); assert.equal(projection(ledger, "2026-10-05T08:00:00.001Z", "breach").deadlines.authorityState, "overdue"); assert.equal(projection(ledger, NOW, "breach").readiness.ready, false); });
test("later awareness edits cannot reset the already documented clock", () => { let ledger = create(createPrivacyLedger(), "breach", BREACH); ledger = command(ledger, { action: "update", id: "breach", payload: { controllerAwareAt: "2026-10-03T07:00:00Z" } }); const deadlines = projection(ledger, NOW, "breach").deadlines; assert.equal(deadlines.authorityDueAt, "2026-10-05T08:00:00.000Z"); assert.equal(deadlines.effectiveControllerAwareAt, "2026-10-02T08:00:00.000Z"); });
for (const bad of ["2026-10-03T08:00:00", "2026-10-03 08:00:00Z", "2026-10-03T24:00:00Z", "2026-02-30T08:00:00Z", "2026-10-03T08:00:00+15:00", "2026-10-03T08:00:00+14:01"]) test(`unambiguous instant required: ${bad}`, () => { expectCode(() => create(createPrivacyLedger(), "breach", { controllerAwareAt: bad }), "INVALID_INSTANT"); });
test("missing awareness never invents a due date or clears review", () => { const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, controllerAwareAt: null }); const record = projection(ledger, NOW, "breach"); assert.equal(record.deadlines.authorityDueAt, null); assert.equal(record.deadlines.authorityState, "unknown"); assert.ok(record.readiness.issues.some((entry) => entry.code === "AWARENESS_MISSING")); });
test("future incident times cannot pass review", () => { const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, controllerAwareAt: "2026-10-04T08:00:00Z" }); assert.ok(projection(ledger, NOW, "breach").readiness.issues.some((entry) => entry.code === "FUTURE_INCIDENT_TIME")); });
test("unknown or high risk cannot justify non-reporting; genuine no-risk needs reasoning", () => { for (const risk of ["unknown", "risk", "high"]) { const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, risk, authorityDecision: "not_required", authorityReason: "Not enough evidence" }); assert.equal(projection(ledger, NOW, "breach").readiness.ready, false); } const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, risk: "none", authorityDecision: "not_required", authorityReason: "Synthetisch begründetes fehlendes Risiko" }); assert.equal(projection(ledger, NOW, "breach").deadlines.authorityState, "not_required"); assert.equal(projection(ledger, NOW, "breach").readiness.ready, true); });
test("high-risk authority and subject decisions remain separate", () => { const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, risk: "high", subjectDecision: "notify", subjectReason: "" }); const record = projection(ledger, NOW, "breach"); assert.equal(record.deadlines.subjectsState, "pending_immediate"); assert.equal(record.deadlines.authorityState, "pending"); assert.equal(record.readiness.ready, true); });
test("public notice exemption requires evidence of actual public communication", () => { let ledger = create(createPrivacyLedger(), "breach", { ...BREACH, risk: "high", subjectDecision: "exemption", subjectException: "public_notice", subjectReason: "Synthetische dokumentierte Prüfung" }); assert.equal(projection(ledger, NOW, "breach").deadlines.subjectsState, "pending_public_notice"); ledger = command(ledger, { action: "record_notification", id: "breach", decision: { channel: "subjects", phase: "public_notice", sentAt: NOW, evidenceReference: "PUBLICATION-RECEIPT" } }); assert.equal(projection(ledger, NOW, "breach").deadlines.subjectsState, "recorded_public_notice"); });
test("processor must notify controller immediately and gets no own 72-hour allowance", () => { let ledger = create(createPrivacyLedger(), "breach", { ...BREACH, roleInIncident: "processor", processorAwareAt: NOW, controllerAwareAt: null, authorityDecision: "unknown", subjectDecision: "unknown" }); const record = projection(ledger, NOW, "breach"); assert.equal(record.deadlines.authorityDueAt, null); assert.equal(record.deadlines.processorState, "pending_immediate"); assert.equal(record.deadlines.authorityState, "controller_responsibility"); ledger = command(ledger, { action: "record_notification", id: "breach", decision: { channel: "controller", phase: "initial", sentAt: NOW, evidenceReference: "CONTROLLER-RECEIPT" } }); assert.equal(projection(ledger, NOW, "breach").deadlines.processorState, "recorded"); expectCode(() => command(ledger, { action: "record_notification", id: "breach", decision: { channel: "authority", phase: "initial", sentAt: NOW, evidenceReference: "WRONG-CHANNEL" } }), "INVALID_NOTIFICATION"); });
test("draft incidents can record actual dispatch even before slow independent review", () => { const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, risk: "unknown", authorityDecision: "unknown" }); const next = command(ledger, { action: "record_notification", id: "breach", decision: { channel: "authority", phase: "initial", sentAt: NOW, evidenceReference: "ACTUAL-DISPATCH" } }); assert.equal(next.records.find((entry) => entry.id === "breach").status, "draft"); assert.equal(projection(next, NOW, "breach").deadlines.authorityState, "recorded"); });
test("late initial dispatch needs reason and is marked recorded late", () => { const ledger = create(createPrivacyLedger(), "breach", BREACH); const decision = { channel: "authority", phase: "initial", sentAt: "2026-10-05T08:00:00.001Z", evidenceReference: "LATE-RECEIPT" }; expectCode(() => command(ledger, { action: "record_notification", id: "breach", decision }, author, "2026-10-05T09:00:00Z"), "LATE_REASON_REQUIRED"); const next = command(ledger, { action: "record_notification", id: "breach", decision: { ...decision, lateReason: "Synthetisch dokumentierte Verzögerung" } }, author, "2026-10-05T09:00:00Z"); assert.equal(projection(next, "2026-10-05T09:00:00Z", "breach").deadlines.authorityState, "recorded_late"); });
test("dispatch exactly at deadline is recorded without late reason", () => { const ledger = create(createPrivacyLedger(), "breach", BREACH); const next = command(ledger, { action: "record_notification", id: "breach", decision: { channel: "authority", phase: "initial", sentAt: "2026-10-05T08:00:00Z", evidenceReference: "ON-TIME" } }, author, "2026-10-05T08:00:00Z"); assert.equal(projection(next, "2026-10-05T08:00:00Z", "breach").deadlines.authorityState, "recorded"); });
test("phased reporting has a first report and does not restart deadline", () => { let ledger = create(createPrivacyLedger(), "breach", BREACH); const first = { channel: "authority", phase: "initial", sentAt: NOW, evidenceReference: "INITIAL-RECEIPT" }; expectCode(() => command(ledger, { action: "record_notification", id: "breach", decision: { ...first, phase: "follow_up" } }), "INVALID_NOTIFICATION"); ledger = command(ledger, { action: "record_notification", id: "breach", decision: first }); ledger = command(ledger, { action: "record_notification", id: "breach", decision: { ...first, phase: "follow_up", evidenceReference: "FOLLOW-UP-RECEIPT" } }); assert.equal(projection(ledger, NOW, "breach").deadlines.authorityDueAt, "2026-10-05T08:00:00.000Z"); });
test("fake or duplicate notification evidence is rejected", () => { let ledger = create(createPrivacyLedger(), "breach", BREACH); const first = { channel: "authority", phase: "initial", sentAt: NOW, evidenceReference: "RECEIPT" }; expectCode(() => command(ledger, { action: "record_notification", id: "breach", decision: { ...first, evidenceReference: "" } }), "INVALID_FIELD"); expectCode(() => command(ledger, { action: "record_notification", id: "breach", decision: { ...first, sentAt: "2026-10-03T09:00:00Z" } }), "INVALID_NOTIFICATION"); ledger = command(ledger, { action: "record_notification", id: "breach", decision: first }); expectCode(() => command(ledger, { action: "record_notification", id: "breach", decision: first }), "DUPLICATE_NOTIFICATION"); });
test("closure cannot hide outstanding notices, follow-up or remediation", () => { let ledger = approve(create(createPrivacyLedger(), "breach", { ...BREACH, risk: "high", subjectDecision: "notify" }), "breach"); expectCode(() => command(ledger, { action: "close", id: "breach", decision: { reason: "Done" } }), "CLOSE_INCOMPLETE"); for (const channel of ["authority", "subjects"]) ledger = command(ledger, { action: "record_notification", id: "breach", decision: { channel, phase: "initial", sentAt: NOW, evidenceReference: `RECEIPT-${channel}` } }); ledger = command(ledger, { action: "close", id: "breach", decision: { reason: "Synthetisch vollständig abgeschlossen" } }); assert.equal(projection(ledger, NOW, "breach").status, "closed"); assert.equal(projection(ledger).summary.openIncidents, 0); ledger = command(ledger, { action: "archive", id: "breach", decision: { reason: "Synthetischer abgeschlossener Altfall" } }); assert.equal(projection(ledger, NOW, "breach").status, "archived"); });
test("open or unclassified breaches cannot be archived away", () => { for (const breachConfirmed of ["yes", "unknown"]) { const ledger = create(createPrivacyLedger(), "breach", { ...BREACH, breachConfirmed }); expectCode(() => command(ledger, { action: "archive", id: "breach", decision: { reason: "Hide" } }), "ARCHIVE_OPEN_INCIDENT"); } });
test("no works council does not infer consent or GDPR legal basis", () => { let ledger = activityLedger(); ledger = create(ledger, "works_agreement", agreementPayload(ledger, { consentCoverage: "unknown", consentEvidenceReference: "", gdprBasis: "" })); const record = projection(ledger, NOW, "works_agreement"); assert.equal(record.readiness.ready, false); assert.ok(record.readiness.issues.some((entry) => entry.code === "INDIVIDUAL_CONSENTS_MISSING")); });
test("complete current individual consent evidence permits an independent process review", () => { let ledger = activityLedger(); ledger = approve(create(ledger, "works_agreement", agreementPayload(ledger)), "works_agreement"); assert.equal(projection(ledger, NOW, "works_agreement").readiness.releaseReady, true); });
test("expired, terminated, future or incomplete consent coverage is not effective", () => { for (const patch of [{ validTo: "2026-10-02" }, { validFrom: "2026-10-04" }, { agreementStatus: "terminated" }, { consentCoverage: "incomplete" }, { signatoriesConfirmed: false }]) { let ledger = activityLedger(); ledger = create(ledger, "works_agreement", agreementPayload(ledger, patch)); assert.equal(projection(ledger, NOW, "works_agreement").readiness.ready, false); } });
test("ArbVG96 consent cannot be replaced by a conciliation decision", () => { let ledger = orgLedger(); ledger = command(ledger, { action: "update", id: "organization", payload: { worksCouncil: "present" } }); ledger = approve(ledger, "organization"); ledger = approve(create(ledger, "activity", ACTIVITY), "activity"); ledger = create(ledger, "works_agreement", agreementPayload(ledger, { worksCouncil: "present", assessment: "arbvg96", legalInstrument: "conciliation", consentCoverage: "not_required" })); assert.ok(projection(ledger, NOW, "works_agreement").readiness.issues.some((entry) => entry.code === "ARbVG96_NOT_SUBSTITUTABLE")); });
test("ArbVG96a conciliation is distinct and organizational council status must match", () => { let ledger = orgLedger(); ledger = command(ledger, { action: "update", id: "organization", payload: { worksCouncil: "present" } }); ledger = approve(ledger, "organization"); ledger = approve(create(ledger, "activity", ACTIVITY), "activity"); ledger = create(ledger, "works_agreement", agreementPayload(ledger, { worksCouncil: "present", assessment: "arbvg96a", legalInstrument: "conciliation", consentCoverage: "not_required" })); assert.equal(projection(ledger, NOW, "works_agreement").readiness.ready, true); ledger = command(ledger, { action: "update", id: "works_agreement", payload: { worksCouncil: "absent" } }); assert.ok(projection(ledger, NOW, "works_agreement").readiness.issues.some((entry) => entry.code === "WORKS_COUNCIL_CONFLICT")); });
for (const [label, mutate] of [["payload", (l) => { l.records[0].payload.notes = "Tamper"; }], ["history", (l) => { l.records[0].history[0].payload.notes = "Tamper"; }], ["receipt", (l) => { l.receiptSha256 = "f".repeat(64); }], ["actor", (l) => { l.events[0].actor.employeeNumber = "FORGED"; }], ["missing event", (l) => { l.events.pop(); l.revision--; }], ["record status", (l) => { l.records[0].status = "draft"; }]]) test(`hash chain rejects altered ${label}`, () => { const ledger = JSON.parse(JSON.stringify(orgLedger())); mutate(ledger); assert.throws(() => verifyPrivacyLedger(ledger), PrivacyOrganizationError); });
test("archive retains immutable revisions; no edits to archived records", () => { const first = create(createPrivacyLedger(), "activity", { title: "Mistaken draft" }); const next = command(first, { action: "archive", id: "activity", decision: { reason: "No longer required" } }); assert.equal(next.records.find((record) => record.id === "activity").history.length, 2); expectCode(() => command(next, { action: "update", id: "activity", payload: { title: "Overwrite" } }), "INVALID_STATE"); });
test("record revision limit prevents unbounded history", () => { let ledger = createPrivacyLedger(); for (let index = 0; index < 127; index++) ledger = command(ledger, { action: "update", id: "organization", payload: { notes: `Synthetic revision ${index}` } }); expectCode(() => command(ledger, { action: "update", id: "organization", payload: {} }), "REVISION_LIMIT"); });
test("record count limit is explicit and does not delete old evidence", () => { let ledger = createPrivacyLedger(); for (let index = 0; index < 255; index++) ledger = create(ledger, "activity", { title: "Synthetic capacity fixture" }, `record-${index}`); assert.equal(ledger.records.length, 256); expectCode(() => create(ledger, "activity", {}, "overflow"), "RECORD_LIMIT"); });
test("command cannot smuggle actor or payload through approval", () => { let ledger = command(command(createPrivacyLedger(), { action: "update", id: "organization", payload: ORG }), { action: "submit", id: "organization" }); expectCode(() => command(ledger, { action: "approve", id: "organization", actor: reviewer, decision: { reason: "Fake actor" } }, reviewer), "UNKNOWN_FIELD"); expectCode(() => command(ledger, { action: "approve", id: "organization", payload: { controllerName: "Changed" }, decision: { reason: "Fake basis" } }, reviewer), "INVALID_ACTION"); });

test("independent incident review never turns open notifications or remediation into green organization readiness", () => {
  let ledger = approve(create(orgLedger(), "breach", { ...BREACH, risk: "high", subjectDecision: "notify" }), "breach");
  let record = projection(ledger, NOW, "breach");
  assert.equal(record.readiness.ready, true); assert.equal(record.status, "approved");
  assert.equal(record.readiness.releaseReady, false); assert.equal(record.readiness.operationalComplete, false);
  assert.equal(projection(ledger).summary.releaseReady, false);
  for (const channel of ["authority", "subjects"]) ledger = command(ledger, { action: "record_notification", id: "breach", decision: { channel, phase: "initial", sentAt: NOW, evidenceReference: `FINAL-${channel}` } });
  assert.equal(projection(ledger, NOW, "breach").readiness.releaseReady, true); assert.equal(projection(ledger).summary.releaseReady, true);
  for (const patch of [{ followUpStatus: "pending" }, { followUpReason: "" }, { remediationComplete: false }]) {
    let changed = command(ledger, { action: "update", id: "breach", payload: patch }); changed = approve(changed, "breach");
    assert.equal(projection(changed, NOW, "breach").readiness.ready, true);
    assert.equal(projection(changed, NOW, "breach").readiness.releaseReady, false);
    assert.equal(projection(changed).summary.releaseReady, false);
  }
});

test("DPIA and agreement require current VVT review even when immutable content hash is unchanged", () => {
  let ledger = approve(create(orgLedger(), "activity", { ...ACTIVITY, reviewOn: "2026-10-03" }), "activity");
  ledger = approve(create(ledger, "dpia", dpiaPayload(ledger)), "dpia");
  ledger = approve(create(ledger, "works_agreement", agreementPayload(ledger)), "works_agreement");
  const original = ledger.records.find((record) => record.id === "activity").contentSha256;
  for (const id of ["dpia", "works_agreement"]) {
    assert.equal(projection(ledger, NOW, id).readiness.releaseReady, true);
    const record = projection(ledger, "2026-10-04T08:00:00Z", id);
    assert.equal(record.payload.activitySha256, original); assert.equal(record.readiness.releaseReady, false);
    assert.ok(record.readiness.issues.some((entry) => entry.code === "VVT_REVIEW_NOT_CURRENT"));
  }
  assert.equal(ledger.records.find((record) => record.id === "activity").contentSha256, original);
});
