'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),publicRoot=path.join(root,'public');
test('simulation UI uses real protected backend variants and a shared GP print window',{
 skip:process.env.GP_BWL_BROWSER_TEST!=='1',timeout:120000,
},async t=>{
 const {simulationFixture}=require('../test-support/sales-bwl-simulation-fixture');
 const source=Array.from({length:12},(_,i)=>({EAN:String(i+42).padStart(13,'0'),Artikelbezeichnung:'BEISPIEL Fernglas '+(8+i%5)+'×'+(25+i),Abverkauf:true,Sortiment:'Abverkauf',DurchschnittEK:String(55+i*3),MWST:1,OhneBestand:false,Sachkonto:false}));
 if(process.env.GP_BWL_CLEAN_SCREENSHOTS!=='1')source[0].Artikelbezeichnung='BEISPIEL <img src=x onerror="window.simXss=1"> Fernglas';
 const stocks=source.flatMap((s,i)=>[{EAN:s.EAN,FilialID:18,FBestand:String(3+i),Bestellt:'0'},{EAN:s.EAN,FilialID:19,FBestand:String(1+i%4),Bestellt:'0'}]);
 const f=await simulationFixture(t,{source,stocks}),store=require('../lib/sales-bwl-simulation-variants-store').createSalesBwlSimulationVariantsStore({access:f.app.provider,vault:f.vault}),preferences=require('../lib/sales-bwl-simulation-preferences-store').createSalesBwlSimulationPreferencesStore({access:f.app.provider,vault:f.vault});
 const app=require('express')();app.use(require('express').json());const calls=[];let release=null,hold=false,holdRename=false;
 app.use('/api',async(req,res,next)=>{calls.push({url:req.url,method:req.method,body:structuredClone(req.body||{})});if(hold&&req.path.endsWith('/calculate')||holdRename&&req.method==='PUT'&&req.path.includes('/variants/'))await new Promise(resolve=>release=resolve);next();});
 require('../lib/sales-bwl-simulation-routes').registerSalesBwlSimulationRoutes(app,{variants:store,preferences,pdf:require('../lib/sales-bwl-simulation-pdf'),sessionFor:()=>f.state.session,assertFresh:()=>f.state.session,assertCsrf:req=>{if(req.get('X-Test-Csrf')!=='yes')throw Object.assign(Error('CSRF'),{status:403,code:'CSRF'});},loadSimulation:(fresh,op,input)=>f.runtime.run(fresh,'bwl-simulation-'+op,input)});
 const styles=['styles.css','mobile-refinements.css','table-layout.css','gp-window.css','gp-print-window.css','gp-data-quality.css','sales-bwl.css'].map(file=>fs.readFileSync(path.join(publicRoot,file),'utf8')).join('\n');
 app.get('/',(req,res)=>res.type('html').send('<!doctype html><meta charset="UTF-8"><style>'+styles+'</style><div class="app-shell"><aside class="sidebar"><div class="brand"><h2>Grabenplaner</h2></div><div class="sidebar-session"><div class="sidebar-session-copy"><strong>BEISPIEL · Filialleitung</strong><span>Lokale Prüfung ohne Produktivdaten</span></div></div><nav class="main-nav"><button class="nav-item">Dashboard</button><button class="nav-item">Verkaufsanalysen</button><button class="nav-item">Artikelstamm</button><button class="nav-item">Artikel-Auswertung</button><button class="nav-item active">BWL-Werkzeuge</button><button class="nav-item">Einkauf &amp; Bestand</button></nav></aside><main class="main-content"><section id="salesBwlView" class="view sales-bwl-view active"><header class="topbar"><div><p class="eyebrow">Verkaufsverwaltung</p><h1>BWL-Werkzeuge</h1><p class="subtitle">Artikel priorisieren, Szenarien vergleichen und Maßnahmen verfolgen.</p></div></header><div id="salesBwlWorkspace"><nav class="bwl-tabs"><button data-bwl-tab="abc">ABC-Analyse</button><button data-bwl-tab="simulation" aria-selected="true">Abverkaufs-Simulation</button><button data-bwl-tab="actions">Maßnahmenliste</button></nav><div id="simulationPane"></div></div></section></main></div>'));
 app.use('/vendor/pdfjs-v6.2.108',require('express').static(path.dirname(require.resolve('pdfjs-dist/package.json'))));app.use(require('express').static(publicRoot));
 const server=http.createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const {chromium}=require(process.env.GP_BROWSER_TEST_MODULE||'playwright'),browser=await chromium.launch({headless:true,...(process.env.GP_BROWSER_EXECUTABLE?{executablePath:process.env.GP_BROWSER_EXECUTABLE}:{}),args:['--no-first-run']});const errors=[];
 try{
  const page=await browser.newPage({viewport:{width:1600,height:1120}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
  for(const file of ['table-layout.js','gp-window-preferences.js','gp-window.js','sales-article-report-pdf-preview.js','gp-print-window.js','gp-data-quality.js','sales-bwl.js','sales-bwl-simulation-print.js','sales-bwl-simulation.js'])await page.addScriptTag({url:'/'+file});
  await page.evaluate(()=>{window.owner='A';window.allowed=true;window.viewActive=true;window.api=async(url,options={})=>{const response=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-Test-Csrf':'yes'}});const result=await response.json();if(!response.ok)throw Object.assign(Error(result.error),{status:response.status});return result;};window.workspace=GrabenplanerBwlSimulation.mount(document.getElementById('simulationPane'),{api,rawApi:(url,options)=>fetch(url,{...options,headers:{'Content-Type':'application/json','X-Test-Csrf':'yes'}}),key:()=>owner,canUse:()=>allowed,active:()=>viewActive,openArticle:number=>window.openedArticle=number});void workspace.activate();});
  const form=page.locator('[data-sim-form]'),submit=form.locator('[type=submit]');await page.waitForFunction(()=>workspace.state().prefsReady);
  const shot=async name=>{if(process.env.GP_BWL_SCREENSHOT_DIR){fs.mkdirSync(process.env.GP_BWL_SCREENSHOT_DIR,{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(process.env.GP_BWL_SCREENSHOT_DIR,name),fullPage:true,animations:'disabled'});}};
  await t.test('real scenario displays separate exact totals and safe article cells',async()=>{await submit.click();await page.waitForFunction(()=>workspace.state().snapshot&&!workspace.state().running);assert.equal(await page.locator('[data-sim-table] tbody tr').count(),24);assert.equal(await page.evaluate(()=>window.simXss),undefined);assert.equal(await page.locator('[data-sim-table] img').count(),0);const state=await page.evaluate(()=>workspace.state());assert.equal(state.snapshot.summary.totals.scenarioNetRevenue.complete,true);assert.equal(state.dirty,false);await page.locator('[data-sim-article]').first().click();assert.equal(await page.evaluate(()=>openedArticle),'000042');});
  await t.test('durable named variants retain old assumptions and compare exact results',async()=>{await page.locator('[data-sim-name]').fill('BEISPIEL Ferngläser · 10 %');await page.locator('[data-sim-save]').click();await page.waitForFunction(()=>workspace.state().currentVariant&&!workspace.state().busy);const first=await page.evaluate(()=>workspace.state().currentVariant.id);await form.locator('[name=discountPercent]').fill('20');await form.locator('[name=discountPercent]').press('Tab');assert.equal(await page.locator('[data-sim-save]').isDisabled(),true);await submit.click();await page.waitForFunction(()=>workspace.state().snapshot?.assumptions.discountPercent==='20'&&!workspace.state().running);await page.locator('[data-sim-name]').fill('BEISPIEL Ferngläser · 20 %');await page.locator('[data-sim-save]').click();await page.waitForFunction(()=>workspace.state().currentVariant?.name.endsWith('20 %')&&!workspace.state().busy);await page.locator('[data-sim-comparison]').selectOption(first);await page.waitForFunction(()=>workspace.state().comparison&&!workspace.state().busy);assert.match(await page.locator('[data-sim-comparison-result]').textContent(),/Gleiche Auswahl/);assert.match(await page.locator('[data-sim-comparison-result]').textContent(),/Differenz/);const stored=await store.get(async()=>f.state.session,first);assert.equal(stored.snapshot.assumptions.discountPercent,'10');await shot('06-simulation-light.png');});
  await t.test('renaming a historical variant retains changed assumptions and blocks mismatched exports',async()=>{await form.locator('[name=discountPercent]').fill('25');await form.locator('[name=discountPercent]').press('Tab');assert.equal(await page.evaluate(()=>workspace.state().dirty),true);holdRename=true;await page.locator('[data-sim-name]').fill('BEISPIEL Ferngläser · 20 % geprüft');await page.locator('[data-sim-rename]').click();await page.waitForFunction(()=>workspace.state().busy);assert.equal(await form.locator('[name=discountPercent]').isDisabled(),true);assert.equal(await submit.isDisabled(),true);while(!release)await new Promise(resolve=>setTimeout(resolve,10));holdRename=false;release();release=null;await page.waitForFunction(()=>!workspace.state().busy);const state=await page.evaluate(()=>workspace.state());assert.equal(state.dirty,true);assert.equal(state.snapshot.assumptions.discountPercent,'20');assert.equal(state.currentVariant.name,'BEISPIEL Ferngläser · 20 % geprüft');assert.equal(await form.locator('[name=discountPercent]').inputValue(),'25');assert.equal(await page.locator('[data-sim-pdf]').isDisabled(),true);assert.equal(await page.locator('[data-sim-save]').isDisabled(),true);await form.locator('[name=discountPercent]').fill('20');await form.locator('[name=discountPercent]').press('Tab');assert.equal(await page.evaluate(()=>workspace.state().dirty),false);});
  await t.test('navigation retains scenario, drafts and comparison without fetching context again',async()=>{const before=calls.filter(c=>c.url.endsWith('/context')).length;await page.evaluate(()=>{viewActive=false;workspace.suspend();});await page.evaluate(()=>{viewActive=true;void workspace.activate();});assert.equal(calls.filter(c=>c.url.endsWith('/context')).length,before);assert.equal(await form.locator('[name=discountPercent]').inputValue(),'20');assert.equal(await page.locator('[data-sim-table] tbody tr').count(),24);assert.ok(await page.evaluate(()=>workspace.state().comparison));});
  await t.test('sortable columns and keyboard widths use account CAS, while conflicts preserve the draft',async()=>{await page.locator('[data-sim-sort=quantity]').click();await page.waitForFunction(()=>workspace.state().version>=1);await page.locator('[data-gp-column-resize=description]').focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>workspace.state().version>=2);const prior=await preferences.read(async()=>f.state.session);await preferences.write(async()=>f.state.session,{version:prior.version,preferences:prior.preferences});await page.locator('[data-sim-sort=quantity]').click();await page.waitForFunction(()=>!workspace.state().prefsReady);assert.equal(await page.locator('[data-sim-prefs-reload]').isVisible(),true);await page.locator('[data-sim-prefs-reload]').click();await page.waitForFunction(()=>workspace.state().prefsReady);});
  await t.test('shared print renders actual historical variant and comparison with all rows',async()=>{await page.locator('[data-sim-pdf]').click();const shell=page.locator('[data-gp-print-id=bwl-simulation-pdf]');await page.waitForFunction(()=>!document.querySelector('[data-gp-print-id=bwl-simulation-pdf] [data-gp-print-download]').disabled);assert.equal(await shell.locator('canvas').count(),1);assert.match(await shell.locator('[data-gp-print-count]').textContent(),/24 Zeilen/);const body=calls.filter(c=>c.url.endsWith('/pdf-preview')).at(-1).body;assert.ok(body.variantId&&body.comparisonVariantId);assert.equal(Object.hasOwn(body,'rows'),false);await shot('09-simulation-print-landscape.png');const pending=page.waitForEvent('download');await shell.locator('[data-gp-print-download]').click();const download=await pending;const bytes=fs.readFileSync(await download.path());assert.equal(bytes.subarray(0,5).toString(),'%PDF-');if(process.env.GP_BWL_SCREENSHOT_DIR)fs.writeFileSync(path.join(process.env.GP_BWL_SCREENSHOT_DIR,'simulation-landscape.pdf'),bytes);await shell.locator('[name=orientation]').selectOption('portrait');await page.waitForFunction(()=>!document.querySelector('[data-gp-print-id=bwl-simulation-pdf] [data-gp-print-download]').disabled);await shot('10-simulation-print-portrait.png');const portraitPending=page.waitForEvent('download');await shell.locator('[data-gp-print-download]').click();const portraitDownload=await portraitPending;if(process.env.GP_BWL_SCREENSHOT_DIR)fs.writeFileSync(path.join(process.env.GP_BWL_SCREENSHOT_DIR,'simulation-portrait.pdf'),fs.readFileSync(await portraitDownload.path()));await shell.locator('[data-gp-print-close]').click();await shell.waitFor({state:'hidden'});});
  await t.test('dark and narrow layouts keep comparison controls inside the viewport',async()=>{await page.evaluate(()=>document.documentElement.dataset.activePageTheme='dark');await shot('07-simulation-dark.png');await page.setViewportSize({width:430,height:1000});await page.evaluate(()=>document.documentElement.dataset.activePageTheme='light');assert.equal(await page.locator('.bwl-criteria').evaluate(el=>el.getBoundingClientRect().right>innerWidth+1),false);await shot('08-simulation-narrow.png');await page.setViewportSize({width:1600,height:1120});});
  await t.test('late calculated output after owner change is discarded and private material clears',async()=>{hold=true;await submit.click();await new Promise(resolve=>{const check=()=>release?resolve():setTimeout(check,20);check();});await page.evaluate(()=>{owner='B';workspace.sync();});assert.equal(await page.locator('[data-sim-result]').isVisible(),false);assert.equal(await page.locator('[data-sim-name]').inputValue(),'');hold=false;release();release=null;await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>workspace.state().snapshot),null);await page.evaluate(()=>{allowed=false;workspace.sync();});assert.equal(await submit.isDisabled(),true);});
  assert.deepEqual(errors,[]);
 }finally{release?.();await browser.close();await new Promise(resolve=>server.close(resolve));}
});
