 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),publicRoot=path.join(root,'public');
test('team actions UI retains drafts and uses protected records and private table preferences',{skip:process.env.GP_BWL_BROWSER_TEST!=='1',timeout:120000},async t=>{
 const f=await require('../test-support/sales-bwl-simulation-fixture').simulationFixture(t);f.state.session.role='manager';f.state.session.permissions.push('sales:bwl:actions:write');const fresh=async()=>f.state.session;
 const locations=[{id:'18',label:'18 · BEISPIEL Grabenweg'},{id:'19',label:'19 · BEISPIEL Mitterweg'}],assignees=[{employeeNumber:'101',firstName:'Alex'},{employeeNumber:'102',firstName:'Maria'}];
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Vienna'}).format(new Date()),dueDate=new Date(Date.parse(today+'T00:00:00Z')+7*86400000).toISOString().slice(0,10);
 const store=require('../lib/sales-bwl-actions-store').createSalesBwlActionsStore({access:f.app.provider,vault:f.vault,loadAssignees:async()=>assignees,loadLocations:async()=>locations,today:()=>today});
 const preferences=require('../lib/sales-bwl-actions-preferences-store').createSalesBwlActionsPreferencesStore({access:f.app.provider,vault:f.vault});
 for(const [i,title] of ['Fernglas-Auslage prüfen','ABC-A-Artikel priorisieren','Lagerbestand abstimmen','Aktionsfläche vorbereiten','Abverkaufsprojekt abstimmen','Lieferstand prüfen'].entries()){const r=await store.create(fresh,{id:crypto.randomUUID(),locationId:'18',title:'BEISPIEL '+title,articleNumber:String(i+42).padStart(6,'0'),priority:i%3===0?'high':'normal',dueDate,assigneeNumber:i%2?'102':'101',note:'Prüfung des letzten Datenstands'});if(i===1)await store.update(fresh,'18',r.id,{version:1,status:'in_progress'});}
 const app=require('express')();app.use(require('express').json());const calls=[];let prefConflict=false;
 app.use('/api',(req,res,next)=>{calls.push({url:req.url,method:req.method,body:structuredClone(req.body||{})});if(prefConflict&&req.method==='PUT'&&req.path.endsWith('/preferences'))return res.status(409).json({error:'Ansicht gleichzeitig geändert'});next();});
 require('../lib/sales-bwl-actions-routes').registerSalesBwlActionsRoutes(app,{actions:store,preferences,pdf:require('../lib/sales-bwl-actions-pdf'),sessionFor:()=>f.state.session,assertFresh:()=>f.state.session,assertCsrf:req=>{if(req.get('X-Test-Csrf')!=='yes')throw Object.assign(Error('CSRF'),{status:403});},loadLocations:async()=>locations,loadAssignees:async()=>assignees});
 const styles=['styles.css','mobile-refinements.css','table-layout.css','gp-window.css','gp-print-window.css','sales-bwl.css'].map(file=>fs.readFileSync(path.join(publicRoot,file),'utf8')).join('\n');
 app.get('/',(req,res)=>res.type('html').send('<!doctype html><meta charset="UTF-8"><style>'+styles+'</style><div class="app-shell"><aside class="sidebar"><div class="brand"><h2>Grabenplaner</h2></div><div class="sidebar-session"><div class="sidebar-session-copy"><strong>BEISPIEL · Filialleitung</strong><span>Lokale Prüfung ohne Produktivdaten</span></div></div><nav class="main-nav"><button class="nav-item">Dashboard</button><button class="nav-item">Verkaufsanalysen</button><button class="nav-item">Artikelstamm</button><button class="nav-item">Artikel-Auswertung</button><button class="nav-item active">BWL-Werkzeuge</button><button class="nav-item">Einkauf &amp; Bestand</button></nav></aside><main class="main-content"><section id="salesBwlView" class="view sales-bwl-view active"><header class="topbar"><div><p class="eyebrow">Verkaufsverwaltung</p><h1>BWL-Werkzeuge</h1><p class="subtitle">Artikel priorisieren, Szenarien vergleichen und Maßnahmen verfolgen.</p></div></header><div id="salesBwlWorkspace"><nav class="bwl-tabs"><button data-bwl-tab="abc">ABC-Analyse</button><button data-bwl-tab="simulation">Abverkaufs-Simulation</button><button data-bwl-tab="actions" aria-selected="true">Maßnahmenliste</button></nav><div id="actionsPane" data-bwl-pane="actions"></div></div></section></main></div>'));
 app.use('/vendor/pdfjs-v6.2.108',require('express').static(path.dirname(require.resolve('pdfjs-dist/package.json'))));app.use(require('express').static(publicRoot));
 const server=http.createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const {chromium}=require(process.env.GP_BROWSER_TEST_MODULE||'playwright'),browser=await chromium.launch({headless:true,...(process.env.GP_BROWSER_EXECUTABLE?{executablePath:process.env.GP_BROWSER_EXECUTABLE}:{}),args:['--no-first-run']});const errors=[];
 try{
 const page=await browser.newPage({viewport:{width:1600,height:1120}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 for(const file of ['table-layout.js','gp-window-preferences.js','gp-window.js','sales-article-report-pdf-preview.js','gp-print-window.js','sales-bwl-actions-print.js','sales-bwl-actions.js'])await page.addScriptTag({url:'/'+file});
 await page.evaluate(async()=>{window.actionOwner='one';window.actionVisible=true;window.actionUse=true;window.actionApi=async(url,options={})=>{const response=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-Test-Csrf':'yes'}});const result=await response.json();if(!response.ok)throw Object.assign(Error(result.error),{status:response.status});return result;};window.actions=GrabenplanerBwlActions.mount(document.getElementById('actionsPane'),{api:actionApi,rawApi:(url,options)=>fetch(url,{...options,headers:{'Content-Type':'application/json','X-Test-Csrf':'yes'}}),key:()=>actionOwner,canUse:()=>actionUse,active:()=>actionVisible});await actions.activate();});
 const form=page.locator('[data-action-form]'),filter=page.locator('[data-action-filter]');
 const shot=async name=>{if(process.env.GP_BWL_SCREENSHOT_DIR){fs.mkdirSync(process.env.GP_BWL_SCREENSHOT_DIR,{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(process.env.GP_BWL_SCREENSHOT_DIR,name),fullPage:true,animations:'disabled'});}};
 await t.test('real team rows have compact assignment and status displays',async()=>{assert.equal(await page.locator('[data-action-table] tbody tr').count(),6);assert.match(await page.locator('[data-action-count]').textContent(),/6 Maßnahmen/);assert.match(await page.locator('[data-action-table]').textContent(),/101 · Alex/);await shot('11-actions-light.png');});
 await t.test('a new draft survives navigation and saves literal text without markup',async()=>{await page.locator('[data-action-new]').click();await form.locator('[name=title]').fill('BEISPIEL <img src=x onerror="window.actionXss=1">');await form.locator('[name=note]').fill('BEISPIEL Entwurf bleibt erhalten');await page.evaluate(()=>{actionVisible=false;actions.suspend();});await page.evaluate(async()=>{actionVisible=true;await actions.activate();});assert.equal(await form.locator('[name=note]').inputValue(),'BEISPIEL Entwurf bleibt erhalten');await form.locator('[type=submit]').click();await page.waitForFunction(()=>actions.state().current?.version===1&&!actions.state().busy);assert.equal((await store.list(fresh,{locationId:'18'})).total,7);assert.equal(await page.evaluate(()=>window.actionXss),undefined);assert.equal(await page.locator('[data-action-table] img').count(),0);await form.locator('[name=title]').fill('BEISPIEL Fernglas-Maßnahme');await form.locator('[type=submit]').click();await page.waitForFunction(()=>actions.state().current?.version===2&&!actions.state().busy);assert.equal((await store.get(fresh,'18',await page.evaluate(()=>actions.state().current.id))).title,'BEISPIEL Fernglas-Maßnahme');});
 await t.test('concurrent edits retain the draft and require explicit discard before reload',async()=>{const r=await page.evaluate(()=>actions.state().current);await store.update(fresh,'18',r.id,{version:r.version,title:'BEISPIEL Änderung eines Kollegen'});await form.locator('[name=note]').fill('BEISPIEL ungespeichert');await form.locator('[type=submit]').click();await page.waitForFunction(()=>!actions.state().busy&&!document.querySelector('[data-action-record-reload]').hidden);assert.equal(await form.locator('[name=note]').inputValue(),'BEISPIEL ungespeichert');await page.locator('[data-action-record-reload]').click();await page.locator('[data-action-discard]').click();await page.waitForFunction(()=>actions.state().current?.version===3);await page.evaluate(()=>document.querySelector('[data-action-filter] [type=submit]').click());await page.waitForFunction(()=>actions.state().rows.some(r=>r.version===3));assert.equal(await form.locator('[name=title]').inputValue(),'BEISPIEL Änderung eines Kollegen');});
 await t.test('a dirty branch switch cannot redirect a pending record or a new draft',async()=>{await form.locator('[name=note]').fill('BEISPIEL Filialgebundener Entwurf');await filter.locator('[name=locationId]').selectOption('19');assert.equal(await form.locator('[type=submit]').isDisabled(),true);await page.locator('[data-action-keep]').click();assert.equal(await filter.locator('[name=locationId]').inputValue(),'18');assert.equal(await form.locator('[name=note]').inputValue(),'BEISPIEL Filialgebundener Entwurf');await page.locator('[data-action-cancel]').click();await page.locator('[data-action-discard]').click();await page.locator('[data-action-new]').click();await form.locator('[name=title]').fill('BEISPIEL neuer Filialentwurf');await filter.locator('[name=locationId]').selectOption('19');await page.locator('[data-action-keep]').click();assert.equal(await filter.locator('[name=locationId]').inputValue(),'18');await page.locator('[data-action-cancel]').click();await page.locator('[data-action-discard]').click();});
 await t.test('closing and reopening require a new reason and retain the prior planning note',async()=>{await page.locator('[data-action-edit]').first().click();const r=await page.evaluate(()=>actions.state().current);await form.locator('[name=status]').selectOption('done');assert.equal(await form.locator('[name=outcome]').isVisible(),true);await form.locator('[type=submit]').click();assert.equal(await page.evaluate(()=>actions.state().current.version),r.version);await form.locator('[name=outcome]').fill('BEISPIEL Auslage kontrolliert und umgesetzt');await form.locator('[type=submit]').click();await page.waitForFunction(v=>actions.state().current?.version===v&&!actions.state().busy,r.version+1);let saved=await store.get(fresh,'18',r.id);assert.equal(saved.status,'done');assert.ok(saved.completedAt);assert.match(saved.note,/Auslage kontrolliert/);assert.ok(saved.note.includes(r.note||''));await form.locator('[name=status]').selectOption('open');await form.locator('[name=outcome]').fill('BEISPIEL erneut prüfen nach Preisänderung');await form.locator('[type=submit]').click();await page.waitForFunction(v=>actions.state().current?.version===v&&!actions.state().busy,r.version+2);saved=await store.get(fresh,'18',r.id);assert.equal(saved.status,'open');assert.equal(saved.completedAt,null);assert.match(saved.note,/erneut prüfen/);await page.locator('[data-action-cancel]').click();});
 await t.test('sortable, visible and keyboard resized columns persist, and CAS conflicts preserve the view draft',async()=>{await page.locator('[data-action-sort=title]').click();await page.waitForFunction(()=>actions.state().prefsVersion>=1);await page.locator('summary').filter({hasText:'Spaltenansicht'}).click();await page.locator('[data-action-column=note]').check();await page.waitForFunction(()=>actions.state().prefsVersion>=2);await page.locator('[data-gp-column-resize=title]').focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>actions.state().prefsVersion>=3);const saved=await preferences.read(fresh);assert.ok(saved.preferences.columns.includes('note'));assert.ok(saved.preferences.columnWidths.title);prefConflict=true;await page.locator('[data-action-column=note]').uncheck();await page.waitForFunction(()=>!actions.state().prefsReady);assert.equal(await page.locator('[data-action-prefs-reload]').isVisible(),true);prefConflict=false;await page.locator('[data-action-prefs-reload]').click();await page.waitForFunction(()=>actions.state().prefsReady);assert.equal(await page.locator('[data-action-column=note]').isChecked(),true);await page.locator('summary').filter({hasText:'Spaltenansicht'}).click();});
 await t.test('light, dark and narrow layouts keep the draft editor and table controls accessible',async()=>{await shot('11-actions-light.png');await page.evaluate(()=>document.documentElement.dataset.activePageTheme='dark');await shot('12-actions-dark.png');await page.setViewportSize({width:500,height:1000});await page.evaluate(()=>document.documentElement.dataset.activePageTheme='light');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await shot('13-actions-narrow.png');await page.setViewportSize({width:1600,height:1120});});
 await t.test('standard print previews and downloads the actual complete selection in both orientations',async()=>{await page.locator('[data-action-pdf]').click();const shell=page.locator('[data-gp-print-id=bwl-actions-pdf]');await page.waitForFunction(()=>!document.querySelector('[data-gp-print-id=bwl-actions-pdf] [data-gp-print-download]').disabled);assert.equal(await shell.locator('canvas').count(),1);assert.match(await shell.locator('[data-gp-print-count]').textContent(),/7 Maßnahmen/);const body=calls.filter(c=>c.url.endsWith('/pdf-preview')).at(-1).body;assert.equal(Object.hasOwn(body,'rows'),false);assert.equal(body.query.locationId,'18');await shot('14-actions-print-landscape.png');for(const orientation of ['landscape','portrait']){if(orientation==='portrait'){await shell.locator('[name=orientation]').selectOption('portrait');await shell.locator('[data-gp-print-options] input[value=source]').uncheck();await shell.locator('[data-gp-print-options] input[value=assigneeNumber]').uncheck();await page.waitForFunction(()=>!document.querySelector('[data-gp-print-id=bwl-actions-pdf] [data-gp-print-download]').disabled);await shot('15-actions-print-portrait.png');}const pending=page.waitForEvent('download');await shell.locator('[data-gp-print-download]').click();const download=await pending,bytes=fs.readFileSync(await download.path());assert.equal(bytes.subarray(0,5).toString(),'%PDF-');if(process.env.GP_BWL_SCREENSHOT_DIR)fs.writeFileSync(path.join(process.env.GP_BWL_SCREENSHOT_DIR,'actions-'+orientation+'.pdf'),bytes);}await page.evaluate(()=>{actionVisible=false;actions.suspend();});assert.equal(await shell.isVisible(),false);await page.evaluate(async()=>{actionVisible=true;await actions.activate();});await shell.waitFor({state:'visible'});assert.equal(await shell.locator('[name=orientation]').inputValue(),'portrait');await shell.locator('[data-gp-print-close]').click();await shell.waitFor({state:'hidden'});});
 await t.test('an owner or permission change clears private drafts and team rows',async()=>{await page.locator('[data-action-new]').click();await form.locator('[name=title]').fill('BEISPIEL privater Entwurf');await page.evaluate(()=>{actionOwner='other';actionUse=false;actions.sync();});assert.equal(await form.locator('[name=title]').inputValue(),'');assert.equal(await page.locator('[data-action-table] tbody tr').count(),0);});
 assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
});
