'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),express=require('express');
const Model=require('../public/sales-price-label-project'),Ui=require('../public/sales-price-labels'),Pdf=require('../lib/sales-price-labels-pdf');
const {fixture}=require('../test-support/trade-insights-sqlite'),T=require('../lib/sales-price-label-template-store'),{createSalesPriceLabelProjectStore}=require('../lib/sales-price-label-project-store');
const {createSalesPriceLabelDraftStore}=require('../lib/sales-price-label-draft-store'),{registerSalesPriceLabelsRoutes}=require('../lib/sales-price-labels-routes');
const options=extra=>Ui.normalizeOptions(extra),label=(number='107506',extra={})=>({id:crypto.randomUUID(),articleNumber:number,priceType:'sales',options:options(extra)});
function project(labels=[label(),label()]){return{schemaVersion:1,name:'Private individual labels',labels,selectedLabelId:labels[0]?.id||'',paper:{paper:'A4',paperWidthMm:210,paperHeightMm:297,orientation:'portrait',marginMm:10,gapMm:3},filenameOptions:{stamp:'none',position:'before',separator:'-',suffix:''}};}
const context=number=>T.resolveTemplateSessionContext({employeeNumber:number,isEmployee:true,sessionKind:'employee',permissions:[],scopes:[]},{listBranchAccounts:async()=>[],getEmployeeHomeLocation:async()=>null});
test('UUID label variants retain independent text/images while project bounds and mixed paper placement remain exact',()=>{
 const a=label('107506',{labelWidthMm:90,labelHeightMm:60}),b=label('107506',{labelWidthMm:148,labelHeightMm:210,copies:2,fontId:'spectral'}),p=project([a,b]),n=Model.normalize(p,Ui.normalizeOptions);
 assert.equal(n.labels[1].articleNumber,n.labels[0].articleNumber);assert.notEqual(n.labels[1].id,n.labels[0].id);assert.equal(n.labels[1].options.fontId,'spectral');
 const plan=Model.paperLayout(n);assert.equal(plan.cells.length,3);assert.equal(plan.pageCount,2);for(const c of plan.cells){assert.ok(c.x>=10&&c.y>=10&&c.x+c.width<=200.001&&c.y+c.height<=287.001);}
 for(const bad of [{...p,ownerId:'forged'},{...p,labels:[a,a]},{...p,selectedLabelId:crypto.randomUUID()},{...p,labels:[{...a,priceGross:'1'}]},{...p,labels:[{...a,options:null}]}])assert.throws(()=>Model.normalize(bad,Ui.normalizeOptions));
 assert.throws(()=>Model.paperLayout(Model.normalize(project([label('1',{labelWidthMm:500})]),Ui.normalizeOptions)));
});
test('encrypted owner-only projects survive reconstruction; exact per-project CAS cannot overwrite another window',async t=>{
 const p=await fixture(t),store=createSalesPriceLabelProjectStore({access:p.app.provider,vault:p.vault}),a=await context('42'),b=await context('43'),input=project();
 const saved=await store.create(a,{project:input});assert.equal(saved.version,1);assert.deepEqual((await store.list(a)).projects.map(row=>row.id),[saved.id]);assert.deepEqual((await store.list(b)).projects,[]);await assert.rejects(store.get(b,saved.id),{status:404});
 const reopened=await createSalesPriceLabelProjectStore({access:p.app.provider,vault:p.vault}).get(a,saved.id);assert.deepEqual(reopened.project,saved.project);
 const next=await store.update(a,saved.id,{version:1,project:{...input,name:'New title'}});assert.equal(next.version,2);await assert.rejects(store.update(a,saved.id,{version:1,project:input}),{status:409});
 assert.equal((await store.get(a,saved.id)).project.name,'New title');assert.ok(p.app.database.prepare("SELECT payload FROM trade_annotations WHERE kind LIKE 'price-label-project%'").all().every(row=>!row.payload.includes('Private individual')&&!row.payload.includes('employee:42')));
 await assert.rejects(store.remove(a,saved.id,{version:1}),{status:409});await store.remove(a,saved.id,{version:2});assert.deepEqual((await store.list(a)).projects,[]);await assert.rejects(store.get(a,saved.id),{status:404});
});

test('uniform individual projects retain the exact decimal legacy grid and reject even slightly oversized paper slots',()=>{
 const labels=Array.from({length:3},(_,i)=>label(String(i+1),{labelWidthMm:62.125,labelHeightMm:48.375,copies:13})),p=Model.normalize(project(labels),Ui.normalizeOptions),plan=Model.paperLayout(p),legacy=require('../public/sales-price-label-layout').create(p.labels[0].options,3);
 assert.equal(plan.pageCount,legacy.pageCount);assert.equal(plan.cells.length,legacy.labelCount);plan.cells.forEach((cell,index)=>{const slot=legacy.slot(index);for(const field of ['page','x','y','width','height','copyIndex'])assert.ok(Math.abs(cell[field]-slot[field])<1e-8,field);});
 const tooWide=Model.normalize(project([label('1',{labelWidthMm:190.0001})]),Ui.normalizeOptions);assert.equal(require('../public/sales-price-label-layout').create(tooWide.labels[0].options,1).capacity,0);assert.throws(()=>Model.paperLayout(tooWide));
});
test('nested draft/project image references and late authorization are checked before any persistence',async t=>{
 const p=await fixture(t),a=await context('42'),assetId=crypto.randomUUID(),labels=[label('107506',{imageBoxes:[{assetId,xMm:1,yMm:1,widthMm:5,heightMm:5}]})],calls=[];
 const controls={access:p.app.provider,vault:p.vault,validateImages:async(_ctx,o)=>{calls.push(o.imageBoxes.map(b=>b.assetId));throw Object.assign(Error('revoked image'),{status:404});}};
 const savedDraft={schemaVersion:1,draftId:crypto.randomUUID(),articleNumbers:'107506',priceType:'sales',options:options(),rawSettings:{},filenameOptions:{stamp:'none',position:'before',separator:'-',suffix:''},name:'Draft',library:{mode:'new',templateId:'',templateVersion:null,title:'',visibility:'private',recipients:[]},selectedArticleNumber:'107506',paperPage:0,project:{id:'',version:null,data:project(labels)}};
 const drafts=createSalesPriceLabelDraftStore(controls);await assert.rejects(drafts.save(a,{revision:0,mutationId:crypto.randomUUID(),draft:savedDraft}),{status:404});assert.deepEqual(calls,[[assetId]]);assert.equal((await drafts.get(a)).revision,0);
 const projects=createSalesPriceLabelProjectStore(controls);await assert.rejects(projects.create(a,{project:project(labels)}),{status:404});assert.deepEqual((await projects.list(a)).projects,[]);
 await assert.rejects(projects.create(a,{project:project()},{assertFresh:async()=>{throw Object.assign(Error('expired'),{status:403});}}),{status:403});assert.deepEqual((await projects.list(a)).projects,[]);
});
test('mixed-label PDF uses the same paper plan, independent fonts and text, copies, and current server prices',async()=>{
 const a=label('107506',{fontId:'roboto',freeTextBoxes:[{id:crypto.randomUUID(),text:'First custom text',fontId:'roboto',fontSizePt:8,bold:false,color:'#223344',align:'left',xMm:4,yMm:50,widthMm:70,heightMm:6}]}),b=label('107506',{labelWidthMm:148,labelHeightMm:210,fontId:'spectral',copies:2,headline:'Second variant'}),p=Model.normalize(project([a,b]),Ui.normalizeOptions);
 const instances=p.labels.map((l,index)=>({id:l.id,options:l.options,item:{articleNumber:l.articleNumber,description:'Current article',priceGross:index?'149.00':'129.00',taxRate:'20'}}));
 const bytes=await Pdf.createSalesPriceLabelsPdf({instances,options:instances[0].options});const{getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs'),task=getDocument({data:new Uint8Array(bytes),isEvalSupported:false}),pdf=await task.promise;
 try{assert.equal(pdf.numPages,Model.paperLayout(p).pageCount);const texts=[];for(let index=1;index<=pdf.numPages;index++){const page=await pdf.getPage(index);texts.push((await page.getTextContent()).items.map(i=>i.str).join(' '));assert.ok(Math.abs(page.view[2]-210*Pdf.MM)<.001);assert.ok(Math.abs(page.view[3]-297*Pdf.MM)<.001);}assert.match(texts[0],/129,00/);assert.match(texts[0],/First custom text/);assert.match(texts[0],/149,00/);assert.match(texts[0],/Second variant/);assert.match(texts[1],/149,00/);}finally{await task.destroy();}
});
test('project and draft HTTP boundaries enforce owner rights, CSRF and fresh gross prices for each duplicate variant',async t=>{
 const p=await fixture(t),rights=Object.values(require('../lib/sales-article-catalog-access').SALES_ARTICLE_CATALOG_PERMISSIONS),state={number:'42',amount:'175.00',revoked:false},session=()=>({employeeNumber:state.number,accountId:state.number,sessionKind:'employee',isEmployee:true,role:'employee',permissions:state.revoked?[]:rights,scopes:[]});
 const app=express();app.use(express.json({limit:'1mb'}));registerSalesPriceLabelsRoutes(app,{templateStore:T.createSalesPriceLabelTemplateStore({access:p.app.provider,vault:p.vault}),draftStore:createSalesPriceLabelDraftStore({access:p.app.provider,vault:p.vault}),projectStore:createSalesPriceLabelProjectStore({access:p.app.provider,vault:p.vault}),sessionFor:session,refreshSession:async()=>session(),assertFresh:async()=>{},assertCsrf:req=>{if(req.headers['x-test-csrf']!=='yes')throw Object.assign(Error('csrf'),{status:403});},privateHeaders:res=>res.set('Cache-Control','private, no-store'),listBranchAccounts:async()=>[],getEmployeeHomeLocation:async()=>null,catalog:{getByArticleNumber:async number=>({articleNumber:number,prices:[{priceType:'sales',priceBasis:'gross',currency:'EUR',qualityStatus:'confirmed',amount:state.amount}]})},loadDetail:async a=>({article:{description:'Current camera',priceMatrix:{vatPercent:'20',sales:[{id:'sales',gross:{amount:state.amount,currency:'EUR'}}]},identifiers:[]}}),images:{content:async()=>null},branding:{list:async()=>({kits:[]})}});
 app.use((e,_req,res,_next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const url='http://127.0.0.1:'+server.address().port;
 const request=(path,method='GET',body,csrf=true)=>fetch(url+'/api/sales/price-labels/'+path,{method,headers:{'Content-Type':'application/json',...(csrf?{'X-Test-Csrf':'yes'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 assert.equal((await request('projects','POST',{project:project()},false)).status,403);const created=await request('projects','POST',{project:project()});assert.equal(created.status,200);const saved=await created.json();state.number='43';assert.equal((await request('projects/'+saved.id)).status,404);state.number='42';state.revoked=true;assert.equal((await request('projects')).status,403);state.revoked=false;
 const exported=await request('projects/export.pdf','POST',{project:saved.project,name:'Project'});assert.equal(exported.status,200);const{getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs'),task=getDocument({data:new Uint8Array(await exported.arrayBuffer()),isEvalSupported:false}),pdf=await task.promise;try{const text=(await(await pdf.getPage(1)).getTextContent()).items.map(i=>i.str).join(' ');assert.equal((text.match(/175,00/g)||[]).length,2);}finally{await task.destroy();}
 assert.equal((await request('projects/export.pdf','POST',{project:{...saved.project,labels:saved.project.labels.map(l=>({...l,priceGross:'1'}))},name:'Forged'})).status,400);
});
