 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),publicRoot=path.join(root,'public');
test('BWL source workflows create trusted team actions and refuse stale source or removed rights',{skip:process.env.GP_BWL_BROWSER_TEST!=='1',timeout:120000},async t=>{
 const f=await require('../test-support/sales-bwl-simulation-fixture').simulationFixture(t);f.state.session.role='manager';f.state.session.permissions.push('sales:bwl:actions:write');const fresh=async()=>f.state.session;
 const locations=[{id:'18',label:'18 · BEISPIEL Grabenweg'},{id:'19',label:'19 · BEISPIEL Mitterweg'}],assignees=[{employeeNumber:'101',firstName:'Alex'},{employeeNumber:'102',firstName:'Maria'}];
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Vienna'}).format(new Date()),dueDate=new Date(Date.parse(today+'T00:00:00Z')+7*86400000).toISOString().slice(0,10);
 let abc;
 const store=require('../lib/sales-bwl-actions-store').createSalesBwlActionsStore({access:f.app.provider,vault:f.vault,loadAssignees:async()=>assignees,loadLocations:async()=>locations,today:()=>today,loadSourceHint:(_fresh,locationId,sourceHint,tx)=>sourceHint.kind==='inventory'?f.runtime.run(_fresh,'bwl-actions-source',{locationId,sourceHint},{executor:tx}):abc.sourceHint(sourceHint.exportToken,sourceHint.rowId,locationId,{executor:tx})});
 const preferences=require('../lib/sales-bwl-actions-preferences-store').createSalesBwlActionsPreferencesStore({access:f.app.provider,vault:f.vault});
 for(const [i,title] of ['Fernglas-Auslage prüfen','ABC-A-Artikel priorisieren','Lagerbestand abstimmen','Aktionsfläche vorbereiten','Abverkaufsprojekt abstimmen','Lieferstand prüfen'].entries()){const r=await store.create(fresh,{id:crypto.randomUUID(),locationId:'18',title:'BEISPIEL '+title,articleNumber:String(i+42).padStart(6,'0'),priority:i%3===0?'high':'normal',dueDate,assigneeNumber:i%2?'102':'101',note:'Prüfung des letzten Datenstands'});if(i===1)await store.update(fresh,'18',r.id,{version:1,status:'in_progress'});}
 const app=require('express')();app.use(require('express').json());const calls=[];let prefConflict=false;
 app.use('/api',(req,res,next)=>{calls.push({url:req.url,method:req.method,body:structuredClone(req.body||{})});if(prefConflict&&req.method==='PUT'&&req.path.endsWith('/preferences'))return res.status(409).json({error:'Ansicht gleichzeitig geändert'});next();});
 require('../lib/sales-bwl-actions-routes').registerSalesBwlActionsRoutes(app,{actions:store,preferences,pdf:require('../lib/sales-bwl-actions-pdf'),sessionFor:()=>f.state.session,assertFresh:()=>f.state.session,assertCsrf:req=>{if(req.get('X-Test-Csrf')!=='yes')throw Object.assign(Error('CSRF'),{status:403});},loadLocations:async()=>locations,loadAssignees:async()=>assignees});
 const checkedLines=Array.from({length:4},(_,i)=>({id:'line-'+i,businessDate:today,locationId:i%2?'19':'18',articleNumber:String(42+Math.floor(i/2)).padStart(6,'0')}));
 const backend={source:{scopeId:'grabenplaner-main',locations},epoch:async()=>['synthetic-checked-cash-1'],search:async()=>checkedLines,
 service:()=>({detail:async id=>{const row=checkedLines.find(r=>r.id===id);if(!row)return {fields:{}};return {table:'Umsatz_Kasse_Details',provenance:{businessDate:today,parentId:'head'},fields:{RepID:id,EAN:row.articleNumber,Artikelbezeichnung:'BEISPIEL Fernglas '+row.articleNumber,VKMenge:'1',Filialid:row.locationId},references:[{role:'location.filialid',targetId:row.locationId,status:'linked'}]};},receipt:async()=>({canAggregate:true,positions:checkedLines.map((r,i)=>({key:r.id,status:'sale',net:String(150+i*40)})),issues:[]})})};
 abc=require('../lib/persistence/repositories/sales-bwl-abc-workspace').createSalesBwlAbcWorkspace({access:f.app.provider,protection:f.protection,backend,getSession:fresh,scopeId:'grabenplaner-main',today:()=>today,sourceAt:today+'T03:00:00.000Z'});
 const routeDeps={sessionFor:()=>f.state.session,assertFresh:()=>f.state.session,assertCsrf:req=>{if(req.get('X-Test-Csrf')!=='yes')throw Object.assign(Error('CSRF'),{status:403});}};
 require('../lib/sales-bwl-abc-routes').registerSalesBwlAbcRoutes(app,{...routeDeps,preferences:require('../lib/sales-bwl-preferences-store').createSalesBwlPreferencesStore({access:f.app.provider,vault:f.vault}),loadAbc:async(_fresh,op,input)=>{try{return await(op==='context'?abc.metadata():op==='step'?abc.step(input.query,input.cursor):op==='snapshot'?abc.snapshot(input.exportToken):abc.cancel(input.cursor));}catch(error){throw error;}}});
 require('../lib/sales-bwl-simulation-routes').registerSalesBwlSimulationRoutes(app,{...routeDeps,variants:require('../lib/sales-bwl-simulation-variants-store').createSalesBwlSimulationVariantsStore({access:f.app.provider,vault:f.vault}),preferences:require('../lib/sales-bwl-simulation-preferences-store').createSalesBwlSimulationPreferencesStore({access:f.app.provider,vault:f.vault}),loadSimulation:(_fresh,op,input)=>f.runtime.run(_fresh,'bwl-simulation-'+op,input)});
 const styles=['styles.css','mobile-refinements.css','table-layout.css','gp-window.css','gp-print-window.css','sales-bwl.css'].map(file=>fs.readFileSync(path.join(publicRoot,file),'utf8')).join('\n');
 app.get('/',(req,res)=>res.type('html').send('<!doctype html><meta charset="UTF-8"><style>'+styles+'</style><div class="app-shell"><aside class="sidebar"><div class="brand"><h2>Grabenplaner</h2></div><div class="sidebar-session"><strong>BEISPIEL · Filialleitung</strong><p>Lokale Prüfung ohne Produktivdaten</p></div><nav class="main-nav"><button class="nav-item active">BWL-Werkzeuge</button></nav></aside><main class="main-content"><section class="view sales-bwl-view active"><header class="topbar"><div><p class="eyebrow">Verkaufsverwaltung</p><h1>BWL-Werkzeuge</h1><p class="subtitle">Artikel priorisieren, Szenarien vergleichen und Maßnahmen verfolgen.</p></div></header><div id="salesBwlWorkspace"></div></section></main></div>'));
 app.use('/vendor/pdfjs-v6.2.108',require('express').static(path.dirname(require.resolve('pdfjs-dist/package.json'))));app.use(require('express').static(publicRoot));
 const server=http.createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const {chromium}=require(process.env.GP_BROWSER_TEST_MODULE||'playwright'),browser=await chromium.launch({headless:true,...(process.env.GP_BROWSER_EXECUTABLE?{executablePath:process.env.GP_BROWSER_EXECUTABLE}:{}),args:['--no-first-run']});const errors=[];
 try{
 const page=await browser.newPage({viewport:{width:1600,height:1120}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 for(const file of ['date-range-calendar.js','trade-period.js','table-layout.js','gp-window-preferences.js','gp-window.js','sales-article-report-pdf-preview.js','gp-print-window.js','sales-bwl-actions-print.js','sales-bwl-actions.js','sales-bwl-simulation.js','sales-bwl.js'])await page.addScriptTag({url:'/'+file});
 await page.evaluate(async()=>{window.actionOwner='one';window.actionVisible=true;window.actionUse=true;window.actionWrite=true;window.actionApi=async(url,options={})=>{const response=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-Test-Csrf':'yes'}});const result=await response.json();if(!response.ok)throw Object.assign(Error(result.error),{status:response.status});return result;};window.bwl=GrabenplanerSalesBwl.mount(document.getElementById('salesBwlWorkspace'),{api:actionApi,rawApi:(url,options)=>fetch(url,{...options,headers:{'Content-Type':'application/json','X-Test-Csrf':'yes'}}),key:()=>actionOwner,canUse:()=>actionUse,canWriteActions:()=>actionWrite,active:()=>actionVisible,openArticle:n=>window.openedArticle=n});await bwl.activate();});
 const actionForm=page.locator('[data-action-form]'),abcForm=page.locator('[data-abc-form]');
 const shot=async name=>{if(process.env.GP_BWL_SCREENSHOT_DIR){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(process.env.GP_BWL_SCREENSHOT_DIR,name),fullPage:true,animations:'disabled'});}};
 await t.test('ABC sources open a prefilled action and server-authoritative minimal proof persists',async()=>{await abcForm.locator('[type=submit]').click();await page.waitForFunction(()=>bwl.state().snapshot||(!bwl.state().running&&document.querySelector('[data-abc-status]').classList.contains('is-error')));assert.ok(await page.evaluate(()=>bwl.state().snapshot),await page.locator('[data-abc-status]').textContent());assert.equal(await page.locator('[data-abc-action]').count(),4);await page.locator('[data-abc-action]').first().click();await page.waitForFunction(()=>bwl.state().tab==='actions'&&!document.querySelector('[data-action-editor]').hidden);await actionForm.locator('[name=title]').fill('BEISPIEL ABC-Ferngläser priorisieren');await actionForm.locator('[name=note]').fill('BEISPIEL Platzierung und Nachbestellung gemeinsam prüfen');await actionForm.locator('[name=assigneeNumber]').selectOption('101');await shot('16-actions-source-editor.png');await actionForm.locator('[type=submit]').click();await page.waitForFunction(()=>bwl.pane('actions').state().current?.version===1&&!bwl.pane('actions').state().busy);const r=await page.evaluate(()=>bwl.pane('actions').state().current),saved=await store.get(fresh,r.locationId,r.id);assert.equal(saved.source.kind,'abc');assert.match(saved.source.reason,/ABC-Klasse/);assert.doesNotMatch(JSON.stringify(saved.source),/netRevenue|grossMargin|quantity/);assert.ok(saved.source.sourceFingerprint);await page.locator('[data-bwl-tab=abc]').click();await abcForm.locator('[name=aLimit]').fill('70');await abcForm.locator('[name=aLimit]').press('Tab');assert.equal(await page.locator('[data-abc-action]').first().isDisabled(),true);});
 await t.test('current inventory action retains its source and historical variants cannot create stale hints',async()=>{await page.locator('[data-bwl-tab=simulation]').click();const simForm=page.locator('[data-sim-form]');await page.waitForFunction(()=>bwl.pane('simulation').state().prefsReady);await simForm.locator('[type=submit]').click();await page.waitForFunction(()=>bwl.pane('simulation').state().snapshotToken&&!bwl.pane('simulation').state().running);await page.locator('[data-sim-action]').first().click();await page.waitForFunction(()=>bwl.state().tab==='actions'&&document.querySelector('[data-action-form] [name=title]').value.startsWith('Bestand'));await actionForm.locator('[name=title]').fill('BEISPIEL aktuelle Fernglas-Auslage');await actionForm.locator('[type=submit]').click();await page.waitForFunction(()=>bwl.pane('actions').state().current?.source?.kind==='inventory'&&!bwl.pane('actions').state().busy);const saved=await page.evaluate(()=>bwl.pane('actions').state().current);assert.equal(saved.articleNumber,'000042');await page.locator('[data-bwl-tab=simulation]').click();await page.locator('[data-sim-name]').fill('BEISPIEL historische Variante');await page.locator('[data-sim-save]').click();await page.waitForFunction(()=>bwl.pane('simulation').state().currentVariant&&!bwl.pane('simulation').state().busy);assert.equal(await page.locator('[data-sim-action]').first().isDisabled(),true);});
 await t.test('a changed source refuses creation and leaves the action draft available on navigation',async()=>{await page.locator('[data-sim-form] [type=submit]').click();await page.waitForFunction(()=>bwl.pane('simulation').state().snapshotToken&&!bwl.pane('simulation').state().running);await page.locator('[data-sim-action]').first().click();await page.waitForFunction(()=>bwl.state().tab==='actions'&&bwl.pane('actions').state().current===null);await actionForm.locator('[name=title]').fill('BEISPIEL Entwurf mit verändertem Quellenstand');const head=await f.repo.getByArticleNumber('000042');await f.repo.updateManual({input:{currentArticleNumber:'000042',expectedRevision:head.currentRevision,articleNumber:'000042',description:'BEISPIEL neuer Datenstand',identifiers:[],prices:{sales:[]}},actor:'synthetic-owner',timestamp:today+'T00:00:00.000Z',mutationId:crypto.randomUUID()});await actionForm.locator('[type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-action-editor-status]').classList.contains('is-error'));assert.equal(await actionForm.locator('[name=title]').inputValue(),'BEISPIEL Entwurf mit verändertem Quellenstand');assert.equal(await page.evaluate(()=>bwl.pane('actions').state().current),null);await page.locator('[data-bwl-tab=abc]').click();await page.locator('[data-bwl-tab=actions]').click();assert.equal(await actionForm.locator('[name=title]').inputValue(),'BEISPIEL Entwurf mit verändertem Quellenstand');});
 await t.test('withdrawn organizational write rights hide sources and keep only read-only team access',async()=>{f.state.session.permissions=f.state.session.permissions.filter(v=>v!=='sales:bwl:actions:write');await page.evaluate(async()=>{actionWrite=false;actionOwner='fresh';bwl.sync();await bwl.activate();});assert.equal(await page.locator('[data-action-new]').isVisible(),false);await page.locator('[data-action-edit]').first().click();assert.equal(await actionForm.locator('[name=title]').isDisabled(),true);assert.equal(await actionForm.locator('[type=submit]').isDisabled(),true);await page.evaluate(()=>{actionUse=false;bwl.sync();});assert.equal(await page.locator('[data-action-table] tbody tr').count(),0);});
 assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
});
