'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const M=require('../lib/sales-bwl-abc-model');const root=path.resolve(__dirname,'..'),publicRoot=path.join(root,'public');
const authority={read:true,margin:true};
function sample(query,owner){const state=M.accumulator();for(let i=1;i<=40;i++)for(const locationId of query.locationIds)M.accumulate(state,{articleNumber:String(i).padStart(6,'0'),description:i===1&&owner==='A'?'BEISPIEL <img src=x onerror="window.bwlXss=1"> Fernglas':`BEISPIEL Fernglas ${i}`,locationId,location:locationId==='18'?'18 · Beispiel West':'05 · Beispiel Ost',metric:{status:'sale',net:String(10000/(i+1)).slice(0,7)},quantity:String(i%6+1),margin:String(3000/(i+1)).slice(0,7)});M.accumulate(state,{articleNumber:'TEST',description:'Prüfung offen',locationId:'18',location:'18 · Beispiel West',metric:null,quantity:'1',reviewIssues:['UNVERIFIED_RECEIPT']});const snapshot={query,sourceAt:'2026-10-09T03:00:00Z',sourceQuality:{sourceId:'compact-cash',uploadedAt:'2026-09-01T03:00:00Z'},coverage:M.COVERAGE,...M.finish(state,query,{margin:true})};if(owner==='B')snapshot.rows.forEach(row=>row.description=row.description.replace('BEISPIEL','BEISPIEL Konto B'));return snapshot;}
test('ABC UI computes through backend steps, persists layout and isolates retained view state',{
 skip:process.env.GP_BWL_BROWSER_TEST!=='1',timeout:90000,
},async t=>{
 const {chromium}=require(process.env.GP_BROWSER_TEST_MODULE||'playwright'),browser=await chromium.launch({headless:true,...(process.env.GP_BROWSER_EXECUTABLE?{executablePath:process.env.GP_BROWSER_EXECUTABLE}:{}),args:['--no-first-run']});let server;const errors=[];
 const documents=[],pdfRequests=[],stored=new Map(),calls=[],context={available:true,today:'2026-10-09',locations:[{id:'18',label:'18 · Beispiel West'},{id:'05',label:'05 · Beispiel Ost'}],metrics:[{id:'netRevenue',label:'Umsatz netto'},{id:'grossMargin',label:'Rohertrag'}],columns:M.COLUMNS,defaultColumns:M.normalizePreferences({},authority).columns,defaults:{aLimit:80,bLimit:95},limits:M.LIMITS,coverage:M.COVERAGE,sourceAt:'2026-10-09T03:00:00Z',sourceQuality:{sourceId:'compact-cash',uploadedAt:'2026-09-01T03:00:00Z'}};
 try{
  const htmlSource=fs.readFileSync(path.join(publicRoot,'index.html'),'utf8'),start=htmlSource.indexOf('<section id="salesBwlView"'),end=htmlSource.indexOf('<section id="receiptSearchView"',start);assert.ok(start>=0&&end>start);const markup=htmlSource.slice(start,end).replace('class="view sales-bwl-view"','class="view sales-bwl-view active"');
  const styles=['styles.css','mobile-refinements.css','table-layout.css','gp-window.css','gp-print-window.css','gp-data-quality.css','sales-bwl.css'].map(file=>fs.readFileSync(path.join(publicRoot,file),'utf8')).join('\n');
  const html=`<!doctype html><meta charset="UTF-8"><style>${styles}</style><div class="app-shell"><aside class="sidebar"><div class="brand"><h2>Grabenplaner</h2></div><div class="sidebar-session"><div class="sidebar-session-copy"><strong>BEISPIEL · Filialleitung</strong><span>Lokale Prüfung ohne Produktivdaten</span></div></div><nav class="main-nav"><button class="nav-item">Dashboard</button><button class="nav-item">Verkaufsanalysen</button><button class="nav-item">Artikelstamm</button><button class="nav-item">Artikel-Auswertung</button><button class="nav-item active">BWL-Werkzeuge</button><button class="nav-item">Einkauf &amp; Bestand</button></nav></aside><main class="main-content">${markup}</main></div>`;
  server=http.createServer((req,res)=>{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(html);return;}const vendor=url.pathname.startsWith('/vendor/pdfjs-v6.2.108/'),assetRoot=vendor?path.dirname(require.resolve('pdfjs-dist/package.json')):publicRoot;const file=path.resolve(assetRoot,url.pathname.slice(vendor?'/vendor/pdfjs-v6.2.108/'.length:1));if(file.startsWith(assetRoot+path.sep)&&fs.existsSync(file)){res.writeHead(200,{'Content-Type':{'.js':'application/javascript','.mjs':'application/javascript','.wasm':'application/wasm','.woff2':'font/woff2'}[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(file));return;}res.writeHead(404);res.end();});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const page=await browser.newPage({viewport:{width:1600,height:1120}});page.on('pageerror',e=>errors.push(e.message));
  await page.exposeFunction('bwlApi',async(url,options,owner)=>{calls.push({url,options,owner});if(url.endsWith('/context'))return context;if(url.endsWith('/preferences/abc')){const prior=stored.get(owner)||{version:0,preferences:M.normalizePreferences({},authority)};if(options?.method==='PUT'){const value=JSON.parse(options.body);if(value.version!==prior.version)return{failed:true,status:409,message:'Zwischenzeitlich geändert'};const saved={version:prior.version+1,preferences:value.preferences};stored.set(owner,saved);return saved;}return prior;}if(url.endsWith('/step')){const {query,cursor}=JSON.parse(options.body);return cursor?{analysis:{complete:true,processed:81,cursor:null},snapshot:sample(query,owner),exportToken:'safe-'+owner}:{analysis:{complete:false,processed:40,cursor:'cursor-'+owner},snapshot:null,exportToken:null};}if(url.endsWith('/cancel'))return{cancelled:true};throw Error('Unexpected fixture request '+url);});
  if(process.env.GP_BWL_PDF_BROWSER_TEST==='1')await page.exposeFunction('abcPdf',async(body,owner)=>{pdfRequests.push(body);assert.equal(body.exportToken,'safe-'+owner);assert.deepEqual(Object.keys(body).sort(),['columns','direction','exportToken','name','orientation','sort','title']);const P=require('../lib/sales-bwl-abc-pdf'),query=calls.filter(c=>c.owner===owner&&c.url.endsWith('/step')).map(c=>JSON.parse(c.options.body).query).at(-1),snapshot=sample(query,owner);const spec=P.normalize(body,authority),result=await P.render({spec,snapshot,generatedAt:'2026-10-09T12:00:00Z'});documents.push(result);if(process.env.GP_BWL_SCREENSHOT_DIR)fs.writeFileSync(path.join(process.env.GP_BWL_SCREENSHOT_DIR,'abc-'+body.orientation+'.pdf'),result.buffer);return{base64:result.buffer.toString('base64'),pages:result.pages,rows:snapshot.rows.length};});
  await page.goto('http://127.0.0.1:'+server.address().port);for(const file of ['date-range-calendar.js','trade-period.js','table-layout.js',...(process.env.GP_BWL_PDF_BROWSER_TEST==='1'?['gp-window-preferences.js','gp-window.js','sales-article-report-pdf-preview.js','gp-print-window.js','sales-bwl-print.js']:[]),'gp-data-quality.js','sales-bwl.js'])await page.addScriptTag({url:'/'+file});
  await page.evaluate(withPdf=>{window.withPdf=withPdf;window.owner='A';window.allowed=true;window.viewActive=true;window.holdPrefs=false;window.holdStep=false;window.api=async(url,options)=>{const result=await bwlApi(url,options,owner);if(url.endsWith('/preferences/abc')&&!options?.method&&holdPrefs)await new Promise(resolve=>window.releasePrefs=resolve);if(url.endsWith('/step')&&holdStep)await new Promise(resolve=>window.releaseStep=resolve);if(result.failed)throw Object.assign(Error(result.message),{status:result.status});return result;};window.workspace=GrabenplanerSalesBwl.mount(document.getElementById('salesBwlWorkspace'),{api,rawApi:withPdf?async(url,options)=>{const value=await abcPdf(JSON.parse(options.body),owner);return new Response(Uint8Array.from(atob(value.base64),c=>c.charCodeAt(0)),{headers:{'Content-Type':'application/pdf','X-PDF-Pages':String(value.pages),'X-Report-Rows':String(value.rows)}});}:undefined,key:()=>owner,canUse:()=>allowed,active:()=>viewActive});void workspace.activate();},process.env.GP_BWL_PDF_BROWSER_TEST==='1');
  const form=page.locator('[data-abc-form]'),submit=form.locator('[type=submit]');await page.waitForFunction(()=>workspace.state().prefsReady);
  const shot=async name=>{if(process.env.GP_BWL_SCREENSHOT_DIR){await page.evaluate(()=>window.scrollTo(0,0));fs.mkdirSync(process.env.GP_BWL_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.GP_BWL_SCREENSHOT_DIR,name),fullPage:true,animations:'disabled'});}};
  await t.test('two backend batches produce exact classes, a Pareto chart and paging without injected markup',async()=>{await submit.click();await page.waitForFunction(()=>workspace.state().snapshot&&!workspace.state().running);assert.equal(await page.locator('[data-abc-count]').textContent(),'81 Zeilen · 80 gereiht · 1 ohne Rang');assert.equal(await page.locator('[data-abc-table] tbody tr').count(),50);assert.equal(await page.locator('[data-abc-chart] svg').count(),1);assert.equal(await page.evaluate(()=>window.bwlXss),undefined);assert.equal(await page.locator('[data-abc-table] img').count(),0);assert.equal(await page.evaluate(()=>workspace.state().dirty),false);await shot('01-abc-analysis-light.png');await page.locator('[data-abc-next]').click();assert.equal(await page.locator('[data-abc-table] tbody tr').count(),31);await page.locator('[data-abc-prev]').click();});
  await t.test('sorting, ordered column selection and keyboard width resize persist through CAS',async()=>{await page.locator('[data-abc-sort=netRevenue]').click();await page.waitForFunction(()=>workspace.state().version>=1);assert.equal(await page.locator('[data-abc-sort=netRevenue]').textContent(),'Umsatz netto ↑');await page.locator('[data-abc-columns]').locator('..').locator('summary').click();await page.locator('[data-abc-column=quantity]').uncheck();await page.waitForFunction(()=>workspace.state().version>=2);const handle=page.locator('[data-gp-column-resize=description]');await handle.focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>workspace.state().version>=3);assert.ok(await page.evaluate(()=>workspace.state().prefs.columnWidths.description)>320);await page.locator('[data-abc-columns]').locator('..').locator('summary').click();});
  await t.test('navigation preserves complete output, changed criteria keep it visible and no context reload occurs',async()=>{const before=calls.filter(c=>c.url.endsWith('/context')).length;await form.locator('[name=aLimit]').fill('70');await form.locator('[name=aLimit]').press('Tab');assert.equal(await page.evaluate(()=>workspace.state().dirty),true);await page.evaluate(()=>{viewActive=false;workspace.suspend();});await page.evaluate(()=>{viewActive=true;void workspace.activate();});assert.equal(await form.locator('[name=aLimit]').inputValue(),'70');assert.equal(await page.locator('[data-abc-table] tbody tr').count(),50);assert.equal(calls.filter(c=>c.url.endsWith('/context')).length,before);await submit.click();await page.waitForFunction(()=>workspace.state().snapshot.query.aLimit===70&&!workspace.state().running);});
  await t.test('late analysis output is discarded after cancellation',async()=>{await page.evaluate(()=>holdStep=true);await submit.click();await page.waitForFunction(()=>typeof releaseStep==='function');await page.locator('[data-abc-cancel]').click();await page.evaluate(()=>{holdStep=false;releaseStep();delete window.releaseStep;});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>workspace.state().running),false);assert.equal(await page.evaluate(()=>workspace.state().snapshot.query.aLimit),70);});
  await t.test('owner switch blocks early edits until stored layout loads and stale result never paints',async()=>{await page.evaluate(()=>{holdPrefs=true;owner='B';workspace.sync();void workspace.activate();});await page.waitForFunction(()=>typeof releasePrefs==='function');assert.equal(await submit.isDisabled(),true);assert.equal(await page.locator('[data-abc-result]').isVisible(),false);assert.equal(await page.locator('[data-abc-summary]').textContent(),'');await page.evaluate(()=>{holdPrefs=false;releasePrefs();delete window.releasePrefs;});await page.waitForFunction(()=>workspace.state().prefsReady);await submit.click();await page.waitForFunction(()=>workspace.state().snapshot&&!workspace.state().running);assert.match(await page.locator('[data-abc-table]').textContent(),/Konto B/);});
  await t.test('conflicting saved views preserve current draft and require explicit reload',async()=>{const prior=stored.get('B')||{version:0,preferences:M.normalizePreferences({},authority)};stored.set('B',{...prior,version:prior.version+1});await page.locator('[data-abc-sort=quantity]').click();await page.waitForFunction(()=>!workspace.state().prefsReady);assert.equal(await page.evaluate(()=>workspace.state().prefs.sort),'quantity');assert.equal(await page.locator('[data-abc-prefs-reload]').isVisible(),true);await page.locator('[data-abc-prefs-reload]').click();await page.waitForFunction(()=>workspace.state().prefsReady);});
  await t.test('dark and narrow layouts retain readable compact controls',async()=>{await page.evaluate(()=>document.documentElement.dataset.activePageTheme='dark');assert.equal(await page.locator('.bwl-card').first().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(24, 37, 31)');assert.equal(await page.locator('.bwl-card h2').first().evaluate(el=>getComputedStyle(el).color),'rgb(237, 244, 241)');await shot('02-abc-analysis-dark.png');await page.setViewportSize({width:430,height:1000});await page.evaluate(()=>document.documentElement.dataset.activePageTheme='light');const overflow=await page.locator('.bwl-criteria').evaluate(el=>el.getBoundingClientRect().right>innerWidth+1);assert.equal(overflow,false);await shot('03-abc-analysis-narrow.png');await page.setViewportSize({width:1600,height:1120});await shot('01-abc-analysis-light.png');});
  if(process.env.GP_BWL_PDF_BROWSER_TEST==='1'){
   const shell=page.locator('[data-gp-print-id=bwl-abc-pdf]'),download=shell.locator('[data-gp-print-download]');
   await t.test('ABC standard print opens with actual pages, all rows and a token-only server request',async()=>{
    await page.locator('[data-abc-pdf]').click();await page.waitForFunction(()=>!document.querySelector('[data-gp-print-download]').disabled);assert.equal(await shell.locator('canvas').count(),1);assert.ok(documents.at(-1).pages>1);assert.match(await shell.locator('[data-gp-print-count]').textContent(),/81 Zeilen/);assert.equal(pdfRequests.at(-1).exportToken,'safe-B');await shot('04-abc-print-landscape.png');
    const pending=page.waitForEvent('download');await download.click();const result=await pending;assert.ok(fs.readFileSync(await result.path()).equals(documents.at(-1).buffer));assert.equal(result.suggestedFilename(),'ABC-Analyse.pdf');
   });
   await t.test('ABC print changes title, filename, columns and portrait preview',async()=>{
    await shell.locator('[name=title]').fill('BEISPIEL Ferngläser · ABC');await shell.locator('[name=filename]').fill('Beispiel-Fernglaeser');await shell.locator('[name=orientation]').selectOption('portrait');
    await shell.locator('[data-gp-print-options] input[value=cumulativePercent]').uncheck();await shell.locator('[data-gp-print-options] input[value=rankingStatus]').uncheck();await shell.locator('[data-gp-print-options] input[value=quantity]').uncheck();await page.waitForFunction(()=>!document.querySelector('[data-gp-print-download]').disabled);assert.equal(pdfRequests.at(-1).orientation,'portrait');assert.equal(pdfRequests.at(-1).title,'BEISPIEL Ferngläser · ABC');assert.ok(!pdfRequests.at(-1).columns.includes('quantity'));await shot('05-abc-print-portrait.png');
   });
   await t.test('navigation retains the print settings and bytes but hides the window until returning',async()=>{
    const prior=documents.length;await page.evaluate(()=>{viewActive=false;workspace.suspend();});assert.equal(await shell.isVisible(),false);await page.evaluate(()=>{viewActive=true;void workspace.activate();});await shell.waitFor({state:'visible'});assert.equal(await shell.locator('[name=title]').inputValue(),'BEISPIEL Ferngläser · ABC');assert.equal(documents.length,prior);await shell.locator('[data-gp-print-close]').click();await shell.waitFor({state:'hidden'});
   });
  }
  await t.test('quality retains the uploaded source and does not prove calendar completeness',async()=>{const panel=page.locator('[data-abc-data-quality]');assert.match(await panel.textContent(),/Hochgeladen am/);assert.match(await panel.textContent(),/Kalenderzeitraums ist nicht nachgewiesen/);assert.equal(await panel.locator('time').getAttribute('datetime'),'2026-09-01T03:00:00Z');await panel.locator('summary').click();assert.match(await panel.textContent(),/Prüfung offen/);});
  await t.test('rights withdrawal clears all result, table and print material',async()=>{await page.evaluate(()=>{allowed=false;workspace.sync();});assert.equal(await page.locator('[data-abc-result]').isVisible(),false);assert.equal(await page.locator('[data-abc-table] tbody tr').count(),0);assert.equal(await submit.isDisabled(),true);assert.equal(await page.evaluate(()=>workspace.state().snapshot),null);assert.equal(await page.locator('[data-abc-data-quality]').textContent(),'');});
  assert.deepEqual(errors,[]);
 }finally{await browser.close();if(server)await new Promise(resolve=>server.close(resolve));}
});
