'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const Ui=require('../public/sales-price-labels');const root=path.resolve(__dirname,'..');
test('Whole price workspace keeps draft, upload target and per-label edits through navigation, reload and named project opening',{skip:process.env.GP_SALES_PRICE_LABEL_EDITOR_BROWSER_TEST!=='1',timeout:90000},async t=>{
 const{chromium}=require(process.env.GP_BROWSER_TEST_MODULE||'playwright'),browser=await chromium.launch({headless:true,...(process.env.GP_BROWSER_EXECUTABLE?{executablePath:process.env.GP_BROWSER_EXECUTABLE}:{}),args:['--no-first-run']});
 let draft={revision:0,draft:null,lastMutationId:null},projects=[],assetId=crypto.randomUUID(),openGate=null;const errors=[];
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.on('pageerror',e=>errors.push(e.message));
 await page.exposeFunction('labelApi',async(url,request={})=>{
  const b=request.body?JSON.parse(request.body):null;
  if(url==='/api/sales/price-labels/draft'){if(b){assert.equal(b.revision,draft.revision);draft={revision:draft.revision+1,draft:b.draft,lastMutationId:b.mutationId};}return structuredClone(draft);}
  if(url==='/api/sales/price-labels/templates')return{options:Ui.normalizeOptions({}),filenameOptions:{stamp:'none',position:'before',separator:'-',suffix:''},hasSavedDefaults:false};
  if(url==='/api/sales/price-labels/branding')return{kits:[]};
  if(url==='/api/sales/price-labels/library')return{templates:[],capabilities:{create:true,ownBranch:false},recipients:[]};
  if(url==='/api/sales/price-labels/images')return{images:[{assetId,width:200,height:100,createdAt:new Date().toISOString()}]};
  if(url==='/api/sales/price-labels/articles')return{items:b.articleNumbers.map(articleNumber=>({articleNumber,description:'Kamera '+articleNumber,priceGross:'129.00',brand:'Synthetic',taxRate:'20',ean:'123'})),updatedAt:new Date().toISOString()};
  if(url==='/api/sales/price-labels/projects'){if(b){const row={id:crypto.randomUUID(),version:1,project:b.project};projects.push(row);return row;}return{projects:projects.map(row=>({id:row.id,name:row.project.name,labelCount:row.project.labels.length,version:row.version}))};}
  if(url.startsWith('/api/sales/price-labels/projects/')){const id=url.split('/').at(-1),row=projects.find(r=>r.id===id);if(b){assert.equal(b.version,row.version);row.version++;row.project=b.project;}else if(openGate)await openGate.promise;return structuredClone(row);}
  throw new Error('Unexpected test endpoint '+url);
 });
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lF8AAAAASUVORK5CYII=','base64');
 await page.route('https://label-workspace.test/**',async route=>{const name=new URL(route.request().url()).pathname;if(name==='/')return route.fulfill({contentType:'text/html',body:'<div id="root"></div>'});if(name.startsWith('/fonts/price-labels/'))return route.fulfill({contentType:'font/ttf',body:fs.readFileSync(path.join(root,'public',name))});if(name.startsWith('/api/sales/price-labels/images/'))return route.fulfill({contentType:'image/png',body:png});return route.fulfill({status:404,body:''});});
 async function mount(){await page.goto('https://label-workspace.test/');for(const name of ['sales-price-labels.css','sales-price-label-editor.css','sales-price-label-search-window.css'])await page.addStyleTag({path:path.join(root,'public',name)});
  for(const name of ['sales-price-label-fonts.js','sales-price-label-layout.js','sales-price-label-design.js','sales-price-label-editor.js','sales-price-label-project.js','sales-price-label-working-draft.js','sales-price-labels.js'])await page.addScriptTag({path:path.join(root,'public',name)});
  await page.evaluate(()=>{window.actor='A';window.workspace=GrabenplanerSalesPriceLabels.mount(document.querySelector('#root'),{accessKey:()=>actor,api:(url,o={})=>labelApi(url,{body:o.body,method:o.method}),rawApi:async(url,o)=>{if(url.endsWith('/images')){window.uploadSignal=o.signal;await new Promise(resolve=>window.finishUpload=resolve);return{json:async()=>({image:window.uploadImage})};}window.exportBody=JSON.parse(o.body);return{blob:async()=>new Blob(['synthetic PDF'],{type:'application/pdf'})};}});});await page.evaluate(()=>workspace.load());await page.waitForFunction(()=>document.querySelector('[data-pl="draft-status"]').textContent.includes('gesichert'));
 }
 try{
  await mount();await page.locator('[name=articleNumbers]').fill('107506');await page.locator('[data-pl=refresh]').click();await page.waitForSelector('[data-pl-element=description]');await page.locator('[data-pl=project-name]').fill('Saved project');
  await page.locator('[data-pl-edit=add-text]').click();await page.locator('[data-pl-edit=text]').fill('Permanent note');await page.locator('[data-pl-edit=text]').dispatchEvent('change');await page.evaluate(()=>workspace.flush());
  const firstId=draft.draft.project.data.selectedLabelId;assert.equal(draft.draft.project.data.labels[0].options.freeTextBoxes[0].text,'Permanent note');
  await page.locator('[data-pl-element=description]').click({button:'right'});assert.equal(await page.locator('.spl-element-toolbar.is-context').count(),1);await page.locator('[data-pl-edit=font]').selectOption('spectral');await page.locator('[data-pl-edit=size]').fill('9');await page.locator('[data-pl-edit=size]').dispatchEvent('change');await page.locator('[data-pl-edit=close]').click();
  await page.evaluate(assetId=>window.uploadImage={assetId,width:200,height:100,mime:'image/png'},assetId);await page.locator('[data-pl-image-input]').setInputFiles({name:'Synthetic.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>typeof finishUpload==='function');
  await page.locator('[data-pl=label-copy]').click();const secondId=await page.locator('[data-pl=project-label]').inputValue();assert.notEqual(secondId,firstId);await page.locator('[name=headline]').fill('SECOND');
  await page.evaluate(()=>{workspace.suspend();document.querySelector('#root').hidden=true;});assert.equal(await page.evaluate(()=>uploadSignal.aborted),false);await page.evaluate(()=>finishUpload());
  await page.waitForFunction(()=>!workspace.hasUnsaved);assert.equal(draft.draft.project.data.labels.find(l=>l.id===firstId).options.imageBoxes.length,1);assert.equal(draft.draft.project.data.labels.find(l=>l.id===secondId).options.imageBoxes.length,0);
  await page.evaluate(()=>{document.querySelector('#root').hidden=false;return workspace.load();});await page.waitForSelector('[data-pl-element=description]');assert.equal(await page.locator('[name=headline]').inputValue(),'SECOND');
  await page.evaluate(()=>workspace.flush());await mount();await page.waitForSelector('[data-pl-element=description]');assert.equal(await page.locator('[data-pl=project-label] option').count(),2);assert.equal(await page.locator('[name=headline]').inputValue(),'SECOND');
  await page.locator('[data-pl=project-label]').selectOption(firstId);assert.equal(await page.locator('[name=headline]').inputValue(),'');assert.equal(await page.locator('[data-pl-element^="image:"]').count(),1);assert.equal(await page.locator('[data-pl-element=description] .spl-element-text').evaluate(n=>n.style.fontFamily.includes('Spectral')),true);
  await page.locator('[data-pl=project-save]').click();await page.waitForFunction(()=>document.querySelector('[data-pl=project-status]').textContent.startsWith('Projekt gespeichert.'));assert.equal(projects[0].project.labels.length,2);
  await page.locator('[data-pl=label-delete]').click();await page.evaluate(()=>workspace.flush());assert.equal(draft.draft.project.data.labels.length,1);
  openGate={};openGate.promise=new Promise(resolve=>openGate.resolve=resolve);await page.locator('[data-pl=project-open]').selectOption(projects[0].id);await page.waitForFunction(()=>document.querySelector('[name=headline]').disabled);
  for(const selector of ['[data-pl=library-select]','[data-pl=library-new]','[data-pl=library-copy]','[data-pl=library-reload]','[data-pl=download]'])assert.equal(await page.locator(selector).isDisabled(),true);
  openGate.resolve();openGate=null;await page.waitForFunction(()=>document.querySelector('[data-pl=project-status]').textContent==='Projekt geöffnet.');assert.equal(await page.locator('[data-pl=project-label] option').count(),2);assert.equal(await page.locator('[name=headline]').isDisabled(),false);
  await page.locator('[data-pl=download]').click();await page.waitForFunction(()=>Boolean(exportBody));assert.equal(await page.evaluate(()=>exportBody.project.labels.length),2);assert.equal(await page.evaluate(()=>exportBody.project.labels[0].options.imageBoxes.length),1);
  await page.evaluate(()=>workspace.flush());await page.locator('[name=labelWidthMm]').fill('');await page.evaluate(()=>workspace.flush());assert.equal(draft.draft.rawSettings.labelWidthMm,'');await mount();assert.equal(await page.locator('[name=labelWidthMm]').inputValue(),'');
  await page.evaluate(()=>workspace.destroy());assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});

test('Price article search preserves navigation state and table layout, uses actual page size and docks blank on explicit close',{skip:process.env.GP_SALES_PRICE_LABEL_EDITOR_BROWSER_TEST!=='1',timeout:60000},async t=>{
 const{chromium}=require(process.env.GP_BROWSER_TEST_MODULE||'playwright'),browser=await chromium.launch({headless:true,...(process.env.GP_BROWSER_EXECUTABLE?{executablePath:process.env.GP_BROWSER_EXECUTABLE}:{}),args:['--no-first-run']});
 const page=await browser.newPage({viewport:{width:1300,height:950}}),errors=[],calls=[],added=[];page.on('pageerror',e=>errors.push(e.message));let stored={revision:0,preferences:require('../public/sales-price-label-search-window').defaults()};
 await page.exposeFunction('tableApi',async(_url,request={})=>{if(request.body){const b=JSON.parse(request.body);assert.equal(b.revision,stored.revision);stored={revision:stored.revision+1,preferences:b.preferences};}return structuredClone(stored);});
 await page.exposeFunction('searchApi',async request=>{calls.push(request);return{items:Array.from({length:Math.min(20,45-request.offset)},(_,i)=>({articleNumber:String(100000+request.offset+i),description:'Synthetic camera '+(request.offset+i),retailGross:'129.00',primaryIdentifier:'EAN'})),total:45,limit:20,offset:request.offset};});
 await page.exposeFunction('addLabel',number=>added.push(number));
 await page.route('https://search-label.test/**',route=>route.fulfill({contentType:'text/html',body:'<div id="root"></div><button id="dock">Artikelsuche</button>'}));await page.goto('https://search-label.test/');
 for(const name of ['gp-window.css','sales-price-label-search-window.css'])await page.addStyleTag({path:path.join(root,'public',name)});
 for(const name of ['gp-window-preferences.js','gp-window.js','table-layout.js','sales-price-label-search-window.js'])await page.addScriptTag({path:path.join(root,'public',name)});
 try{
  await page.evaluate(()=>{window.actor='A';window.onPricePage=true;const prefs=GpWindow.createPreferences({key:()=>actor,canUse:()=>true,read:async()=>({version:1,windows:{}}),write:async g=>{window.savedGeometry=g;}});window.search=GrabenplanerPriceLabelSearchWindow.mount({root:document.querySelector('#root'),api:(u,o={})=>tableApi(u,{body:o.body}),searchArticles:o=>searchApi({query:o.query,offset:o.offset,sort:o.sort,direction:o.direction}),addArticle:n=>addLabel(n),key:()=>actor,canUse:()=>true,active:()=>onPricePage,windowPreferences:prefs,dock:document.querySelector('#dock')});});
  await page.locator('#dock').click();await page.locator('.spl-search-window input[type=search]').fill('Kamera');await page.waitForFunction(()=>document.querySelector('.spl-search-window tbody').children.length===20);assert.equal(calls.at(-1).query,'Kamera');
  await page.locator('[data-spl-search-next]').click();await page.waitForFunction(()=>document.querySelector('[data-spl-search-page]').textContent==='21–40');assert.equal(calls.at(-1).offset,20);
  await page.locator('[data-spl-search-next]').click();await page.waitForFunction(()=>document.querySelector('[data-spl-search-page]').textContent==='41–45');await page.locator('[data-spl-search-prev]').click();await page.waitForFunction(()=>document.querySelector('[data-spl-search-page]').textContent==='21–40');
  await page.locator('[data-spl-add]').first().click();assert.deepEqual(added,['100020']);
  await page.locator('.spl-search-window details summary').click();await page.locator('[data-spl-column=primaryIdentifier]').uncheck();await page.waitForFunction(()=>document.querySelector('.spl-search-window thead tr').children.length===4);await page.waitForTimeout(50);assert.equal(stored.preferences.columns.includes('primaryIdentifier'),false);
  await page.locator('[data-gp-column-resize=description]').focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(50);assert.ok(stored.preferences.columnWidths.description>340);
  await page.evaluate(()=>{onPricePage=false;search.suspend();});assert.equal(await page.locator('.spl-search-window').isVisible(),false);await page.evaluate(()=>{onPricePage=true;search.activate();});assert.equal(await page.locator('.spl-search-window input[type=search]').inputValue(),'Kamera');assert.equal(await page.locator('.spl-search-window tbody tr').count(),20);
  await page.locator('[data-spl-search-min]').click();assert.equal(await page.locator('[data-spl-search-body]').isVisible(),false);await page.locator('[data-spl-search-min]').click();
  await page.locator('[data-spl-search-close]').click();await page.waitForFunction(()=>search.state.docked);await page.locator('#dock').click();assert.equal(await page.locator('.spl-search-window input[type=search]').inputValue(),'');assert.equal(await page.locator('.spl-search-window tbody tr').count(),0);assert.equal(await page.locator('.spl-search-window thead th').count(),4);
  await page.evaluate(()=>{actor='B';search.invalidate();});assert.equal(await page.locator('.spl-search-window').isVisible(),false);assert.deepEqual(await page.evaluate(()=>search.state.rows),[]);await page.evaluate(()=>search.destroy());assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});

test('old project operations cannot unlock a newer open or carry a project intent across actor change during draft flush',{skip:process.env.GP_SALES_PRICE_LABEL_EDITOR_BROWSER_TEST!=='1',timeout:60000},async t=>{
 const{chromium}=require(process.env.GP_BROWSER_TEST_MODULE||'playwright'),browser=await chromium.launch({headless:true,...(process.env.GP_BROWSER_EXECUTABLE?{executablePath:process.env.GP_BROWSER_EXECUTABLE}:{}),args:['--no-first-run']});
 const page=await browser.newPage({viewport:{width:1400,height:1050}}),errors=[],drafts=new Map(),gets=[],getGates=[],draftGates=[];page.on('pageerror',e=>errors.push(e.message));
 const gate=()=>{const value={started:false};value.promise=new Promise(resolve=>value.resolve=resolve);return value;};
 const labels=['OLD','NEW'].map(headline=>{const id=crypto.randomUUID(),labelId=crypto.randomUUID();return{id,version:1,project:{schemaVersion:1,name:headline,labels:[{id:labelId,articleNumber:'107506',priceType:'sales',options:Ui.normalizeOptions({headline})}],selectedLabelId:labelId,paper:{paper:'A4',paperWidthMm:210,paperHeightMm:297,orientation:'portrait',marginMm:10,gapMm:3},filenameOptions:{stamp:'none',position:'before',separator:'-',suffix:''}}};});
 await page.exposeFunction('raceApi',async(url,request={})=>{const owner=request.actor,body=request.body?JSON.parse(request.body):null;
  if(url.endsWith('/draft')){let row=drafts.get(owner)||{revision:0,draft:null,lastMutationId:null};if(body){const hold=owner==='A'?draftGates.shift():null;if(hold){hold.started=true;await hold.promise;}assert.equal(body.revision,row.revision);row={revision:row.revision+1,draft:body.draft,lastMutationId:body.mutationId};drafts.set(owner,row);}return structuredClone(row);}
  if(url.endsWith('/templates'))return{options:Ui.normalizeOptions({}),filenameOptions:{stamp:'none',position:'before',separator:'-',suffix:''},hasSavedDefaults:false};
  if(url.endsWith('/branding'))return{kits:[]};if(url.endsWith('/library'))return{templates:[],capabilities:{create:true,ownBranch:false},recipients:[]};
  if(url.endsWith('/articles'))return{items:body.articleNumbers.map(articleNumber=>({articleNumber,description:'Synthetic camera',priceGross:'129.00',taxRate:'20'}))};
  if(url.endsWith('/projects'))return{projects:owner==='A'?labels.map(row=>({id:row.id,version:1,name:row.project.name,labelCount:1})):[]};
  if(url.includes('/projects/')){gets.push({owner,url});const hold=getGates.shift();if(hold){hold.started=true;await hold.promise;}return structuredClone(labels.find(row=>url.endsWith(row.id)));}throw Error(url);
 });
 await page.route('https://label-race.test/**',route=>route.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));await page.goto('https://label-race.test/');
 for(const name of ['sales-price-labels.css','sales-price-label-editor.css','sales-price-label-search-window.css'])await page.addStyleTag({path:path.join(root,'public',name)});
 for(const name of ['sales-price-label-fonts.js','sales-price-label-layout.js','sales-price-label-design.js','sales-price-label-editor.js','sales-price-label-project.js','sales-price-label-working-draft.js','sales-price-labels.js'])await page.addScriptTag({path:path.join(root,'public',name)});
 try{
  await page.evaluate(()=>{window.actor='A';window.workspace=GrabenplanerSalesPriceLabels.mount(document.querySelector('#root'),{accessKey:()=>actor,api:(u,o={})=>raceApi(u,{actor,body:o.body,method:o.method}),rawApi:async()=>({blob:async()=>new Blob()})});return workspace.load();});
  await page.waitForFunction(()=>document.querySelector('[data-pl=project-open]').options.length===3);await page.locator('[name=articleNumbers]').fill('107506');await page.locator('[data-pl=refresh]').click();await page.waitForSelector('[data-pl-element=description]');await page.evaluate(()=>workspace.flush());
  const old=gate(),fresh=gate();getGates.push(old,fresh);await page.locator('[data-pl=project-open]').selectOption(labels[0].id);await page.waitForFunction(()=>document.querySelector('[name=headline]').disabled);while(!old.started)await new Promise(resolve=>setTimeout(resolve,10));
  await page.evaluate(()=>{workspace.suspend();return workspace.load();});await page.waitForFunction(()=>!document.querySelector('[data-pl=project-open]').disabled);await page.locator('[data-pl=project-open]').selectOption(labels[1].id);while(!fresh.started)await new Promise(resolve=>setTimeout(resolve,10));
  old.resolve();await page.waitForTimeout(80);assert.equal(await page.locator('[name=headline]').isDisabled(),true);assert.equal(await page.locator('[data-pl=project-open]').isDisabled(),true);
  fresh.resolve();await page.waitForFunction(()=>document.querySelector('[data-pl=project-status]').textContent==='Projekt geöffnet.');assert.equal(await page.locator('[name=headline]').inputValue(),'NEW');await page.evaluate(()=>workspace.flush());
  const save=gate();draftGates.push(save);await page.locator('[data-pl=project-name]').fill('Unsaved A');while(!save.started)await new Promise(resolve=>setTimeout(resolve,10));await page.locator('[data-pl=project-open]').selectOption(labels[0].id);await page.waitForFunction(()=>document.querySelector('[name=headline]').disabled);
  await page.evaluate(()=>{actor='B';return workspace.load();});save.resolve();await page.waitForTimeout(120);assert.equal(gets.length,2);assert.ok(gets.every(row=>row.owner==='A'));assert.equal(await page.locator('[data-pl=project-name]').inputValue(),'');assert.equal(await page.locator('[data-pl=project-open] option').count(),1);assert.equal(await page.locator('[name=headline]').isDisabled(),false);await page.evaluate(()=>workspace.destroy());assert.deepEqual(errors,[]);
 }finally{getGates.forEach(g=>g.resolve());draftGates.forEach(g=>g.resolve());await browser.close();}
});
