const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), "utf8");

test("v0.92.76: Serverpaket, UI und aktuelle Dokumentation bleiben konsistent", () => {
  const packageJson = JSON.parse(read("package.json"));
  assert.equal(packageJson.version, "0.92.76-beta");
  assert.equal(packageJson.dependencies.sharp, "0.35.3");
  assert.equal(packageJson.dependencies["pdfjs-dist"], "6.2.108");
  assert.match(read("pnpm-workspace.yaml"), /brace-expansion:\s*5\.0\.9/);
  assert.match(read("pnpm-workspace.yaml"), /brace-expansion@5\.0\.9:\s*lib\/vendor-patches\/brace-expansion@5\.0\.9\.patch/);
  assert.match(read("lib/vendor-patches/brace-expansion@5.0.9.patch"), /module\.exports = expand/);

  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.86 Beta starten.cmd")), true);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.85 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.84 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.83 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.82 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.81 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.80 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.79 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.7 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.6 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.5 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.4 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.3 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.2 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.1 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78 Beta starten.cmd")), false);

  const indexHtml = read("public/index.html");
  const readme = read("README.md");
  const securityPolicy = read("SECURITY.md");
  const codespacesDocs = read("CODESPACES.md");
  const codespacesStart = read(".devcontainer/post-start.sh");
  const devcontainer = JSON.parse(read(".devcontainer/devcontainer.json"));
  const serverDocs = read("SERVERBETRIEB.md");
  const usbNotes = read("USB-HINWEISE.txt");
  const versionLog = read("VERSIONS-LOG.md");
  const genericLauncher = read("Dienstplan starten.cmd");

  assert.match(indexHtml, /v0\.92\.76 Beta/);
  assert.match(indexHtml, /id="serverRestartModal"/);
  assert.match(indexHtml, /Nicht gespeicherte Eingaben in geöffneten Browserfenstern können verloren gehen/);
  assert.match(indexHtml, /Vor dem Neustart erstellt Grabenplaner automatisch einen verifizierten Sicherungspunkt/);
  const appJavascript = read("public/app.js");
  assert.match(appJavascript, /monitorActions\.canRestart === true/);
  assert.match(appJavascript, /\/api\/portal\/v1\/server-monitor\/restart/);
  assert.match(appJavascript, /JSON\.stringify\(\{ confirmation: "SERVER_RESTART" \}\)/);
  assert.match(read("server.js"), /sqliteBranchOrderOperations\.ensureConfiguredLocationCatalogContent\(\)/);
  assert.match(readme, /v0\.92\.76 Beta/);
  assert.match(readme, /verwalteten Ubuntu-Einzelserver/i);
  assert.match(readme, /SQLite/);
  assert.match(readme, /PostgreSQL/);
  assert.match(readme, /v0\.87\.0-beta\.legacy\.1/);
  assert.doesNotMatch(readme, /Grabenplaner, drei Betriebsmodelle/);
  assert.doesNotMatch(readme, /Schnellstart unter Windows/);
  assert.match(securityPolicy, /christian\.seiwald\.at@gmail\.com/);
  assert.doesNotMatch(securityPolicy, /Private Vulnerability Reporting/);
  assert.match(securityPolicy, /Legacy/i);
  assert.match(codespacesDocs, /Repository ist öffentlich/i);
  assert.match(codespacesDocs, /automatische Demo-Start erfordert Eigentümer- oder Schreibzugriff/i);
  assert.match(codespacesDocs, /eingeladene Collaborators mit Schreibzugriff/);
  assert.equal(devcontainer.name, "Grabenplaner v0.92.76 Codespaces-Demo");
  assert.equal(Object.hasOwn(devcontainer.features, "ghcr.io/devcontainers/features/sshd:1"), false);
  assert.match(codespacesStart, /EXPECTED_REPOSITORY="christianseiwaldat-collab\/Grabenplaner"/);
  assert.match(codespacesStart, /permissions\.admin or \.permissions\.push/);
  assert.match(read("server.js"), /`dev: \$\{branding\.adminEmail\} · `/);
  assert.match(read("public/assets/webicon.svg"), />GP</);
  assert.match(serverDocs, /Recovery Assurance und System-Center/);
  assert.match(usbNotes, /v0\.87\.0-beta\.legacy\.1/);
  assert.match(usbNotes, /keine automatische Reduktion/i);
  assert.match(genericLauncher, /Grabenplaner v0\.86 Beta starten\.cmd/);
  assert.match(versionLog, /v0\.92\.76 Beta · Quellstand/);
  assert.match(versionLog, /v0\.92\.72 Beta · GitHub-Serverrelease/);
  assert.match(versionLog, /v0\.87\.0-beta\.legacy\.1 · Legacy/);
  assert.equal((versionLog.match(/^## /gm) || []).length, 3);
  assert.doesNotMatch(readme, /<img|docs\//);
  assert.match(read("INTEGRATIONEN.md"), /Planzeit wird niemals als Ist-Zeit/);
  assert.match(read("INTEGRATIONEN.md"), /Ohne zugeordnetes externes Protokoll/);
  assert.match(serverDocs, /keine Verfügbarkeits-, Rechts- oder Sicherheitsgarantie/);
});
