const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), "utf8");

test("v0.88.4: Serverpaket, UI und aktuelle Dokumentation bleiben konsistent", () => {
  const packageJson = JSON.parse(read("package.json"));
  assert.equal(packageJson.version, "0.88.4-beta");
  assert.equal(packageJson.dependencies.sharp, "0.35.3");
  assert.match(read("pnpm-workspace.yaml"), /brace-expansion:\s*5\.0\.8/);
  assert.match(read("pnpm-workspace.yaml"), /brace-expansion@5\.0\.8:\s*lib\/vendor-patches\/brace-expansion@5\.0\.8\.patch/);
  assert.match(read("lib/vendor-patches/brace-expansion@5.0.8.patch"), /module\.exports = expand/);

  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.86 Beta starten.cmd")), true);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.85 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.84 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.83 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.82 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.81 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.80 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.79 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.7 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.6 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.5 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.4 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.3 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.2 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78.1 Beta starten.cmd")), false);
  assert.equal(fs.existsSync(path.join(root, "Grabenplaner v0.78 Beta starten.cmd")), false);

  const indexHtml = read("public/index.html");
  const readme = read("README.md");
  const securityPolicy = read("SECURITY.md");
  const codespacesDocs = read("CODESPACES.md");
  const codespacesStart = read(".devcontainer/post-start.sh");
  const devcontainer = JSON.parse(read(".devcontainer/devcontainer.json"));
  const serverDocs = read("SERVERBETRIEB.md");
  const usbNotes = read("USB-HINWEISE.txt");
  const versionLog = read("VERSIONS-LOG.md");
  const governanceDocs = read("docs/URLAUB-ARBEITSZEIT-DATENSCHUTZ.md");
  const payrollHandoffDocs = read("docs/LOHNUEBERGABE-UND-ELDA-NACHWEIS.md");
  const pilotAcceptanceDocs = read("docs/PILOT-UND-ABNAHME.md");
  const genericLauncher = read("Dienstplan starten.cmd");

  assert.match(indexHtml, /v0\.88\.4 Beta/);
  assert.match(indexHtml, /id="serverRestartModal"/);
  assert.match(indexHtml, /Nicht gespeicherte Eingaben in geöffneten Browserfenstern können verloren gehen/);
  assert.match(indexHtml, /Vor dem Neustart erstellt Grabenplaner automatisch einen verifizierten Sicherungspunkt/);
  const appJavascript = read("public/app.js");
  assert.match(appJavascript, /monitorActions\.canRestart === true/);
  assert.match(appJavascript, /\/api\/portal\/v1\/server-monitor\/restart/);
  assert.match(appJavascript, /JSON\.stringify\(\{ confirmation: "SERVER_RESTART" \}\)/);
  assert.match(readme, /v0\.88\.4 Beta/);
  assert.match(readme, /verwalteten Ubuntu-Einzelserver/i);
  assert.match(readme, /SQLite/);
  assert.match(readme, /PostgreSQL/);
  assert.match(readme, /v0\.87\.0-beta\.legacy\.1/);
  assert.match(readme, /docs\/readme\/dienstplanung\.webp/);
  assert.match(readme, /docs\/readme\/mitarbeiterportal\.webp/);
  assert.doesNotMatch(readme, /Grabenplaner, drei Betriebsmodelle/);
  assert.doesNotMatch(readme, /Schnellstart unter Windows/);
  assert.match(securityPolicy, /christian\.seiwald\.at@gmail\.com/);
  assert.doesNotMatch(securityPolicy, /Private Vulnerability Reporting/);
  assert.match(securityPolicy, /Legacy/i);
  assert.match(codespacesDocs, /Repository ist privat/i);
  assert.match(codespacesDocs, /nur Personen mit Repository-Zugriff/i);
  assert.match(codespacesDocs, /eingeladene Collaborators mit Schreibzugriff/);
  assert.equal(devcontainer.name, "Grabenplaner v0.88.4 Codespaces-Demo");
  assert.equal(Object.hasOwn(devcontainer.features, "ghcr.io/devcontainers/features/sshd:1"), false);
  assert.match(codespacesStart, /EXPECTED_REPOSITORY="christianseiwaldat-collab\/Grabenplaner"/);
  assert.match(codespacesStart, /permissions\.admin or \.permissions\.push/);
  assert.match(read("server.js"), /`dev: \$\{branding\.adminEmail\} · `/);
  assert.match(read("public/assets/webicon.svg"), />GP</);
  assert.match(serverDocs, /Recovery Assurance und System-Center v0\.78/);
  assert.match(usbNotes, /Version v0\.86 Beta/);
  assert.match(usbNotes, /keine automatische Reduktion/i);
  assert.match(genericLauncher, /Grabenplaner v0\.86 Beta starten\.cmd/);
  assert.match(governanceDocs, /Urlaubsgesetz § 2/);
  assert.match(governanceDocs, /Urlaubsgesetz § 4/);
  assert.match(governanceDocs, /Urlaubsgesetz § 8/);
  assert.match(governanceDocs, /Arbeitszeitgesetz § 26/);
  assert.match(governanceDocs, /Datenschutz-Grundverordnung/);
  assert.match(governanceDocs, /Österreichische Datenschutzbehörde/);
  assert.match(governanceDocs, /keine pauschale Zusage vollständiger Rechtskonformität/);
  assert.match(governanceDocs, /Planzeit niemals als Ist-Zeit/);
  assert.match(governanceDocs, /Löschung niemals automatisch/);
  assert.match(payrollHandoffDocs, /grabenplaner\.payroll-period\.v2/);
  assert.match(payrollHandoffDocs, /keine direkte ELDA-Schnittstelle/);
  assert.match(payrollHandoffDocs, /Ohne zugeordnetes externes Protokoll/);
  assert.match(payrollHandoffDocs, /ELDA FAQ/);
  assert.match(pilotAcceptanceDocs, /WCAG 2\.2/);
  assert.match(pilotAcceptanceDocs, /OWASP ASVS 5\.0\.0/);
  assert.match(pilotAcceptanceDocs, /keine pauschale Rechts-, Sicherheits- oder Barrierefreiheitsgarantie/);
  assert.match(versionLog, /v0\.88\.4 Beta/);
  assert.match(versionLog, /v0\.88\.2 Beta/);
  assert.match(versionLog, /v0\.88\.1 Beta/);
  assert.match(versionLog, /v0\.88 Beta/);
  assert.match(versionLog, /v0\.87 Beta/);
  assert.match(versionLog, /v0\.86 Beta/);
  assert.match(versionLog, /v0\.85 Beta/);
  assert.match(versionLog, /v0\.84 Beta/);
  assert.match(versionLog, /v0\.83 Beta/);
  assert.match(versionLog, /v0\.82 Beta/);
  assert.match(versionLog, /v0\.81 Beta/);
  assert.match(versionLog, /v0\.80 Beta/);
  assert.match(versionLog, /v0\.79 Beta/);
  assert.match(versionLog, /v0\.78\.7 Beta/);
  assert.match(versionLog, /v0\.78\.6 Beta/);
  assert.match(versionLog, /v0\.78\.5 Beta/);
  assert.match(versionLog, /v0\.78\.4 Beta/);
  assert.match(versionLog, /v0\.78\.3 Beta/);
  assert.match(versionLog, /v0\.78\.2 Beta/);
  assert.match(versionLog, /v0\.78\.1 Beta/);
  assert.match(versionLog, /v0\.78 Beta/);
  assert.doesNotMatch(readme, /v0\.77 enthält noch keinen nächtlichen/);
});
