"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("v0.91 UI: Filialbestellung trennt Erfassung und Filialleitungs-Konfiguration", () => {
  const html = read("public/portal.html");
  const script = read("public/portal.js");
  const styles = read("public/portal.css");
  const admin = read("public/index.html");
  const adminScript = read("public/app.js");
  const adminStyles = read("public/styles.css");

  assert.match(html, /id="branchOrdersTab"/);
  assert.match(html, /id="branchOrdersView"/);
  assert.match(html, /id="branchVacationTab"/);
  assert.match(html, /id="branchVacationView"/);
  assert.match(html, /id="branchOrderEmployee"/);
  assert.match(html, /id="branchOrderSettingsCard"/);
  assert.match(html, /id="branchOrderHistoryList"/);
  assert.match(html, /id="passwordSettingsCard"/);
  assert.doesNotMatch(html, /branchPasswordShortcut/);
  assert.match(script, /function branchOrderCapabilityEnabled/);
  assert.match(script, /function branchVacationCapabilityEnabled/);
  assert.match(script, /\/api\/portal\/v1\/branch-orders\/catalog/);
  assert.match(script, /\/api\/portal\/v1\/location-dashboard\/vacations/);
  assert.match(script, /catalog\.senderEmail/);
  assert.match(script, /\/api\/portal\/v1\/branch-orders\/settings/);
  assert.match(script, /\/api\/portal\/v1\/branch-orders\/history/);
  assert.match(script, /function captureBranchOrderSettingsDraft/);
  assert.match(script, /passwordSettingsCard.*isOrganizationAccount/s);
  assert.match(script, /loanOverviewColumnCatalog/);
  assert.match(script, /borrowerName/);
  assert.match(admin, /id="organizationAccountBranchOrders"/);
  assert.match(admin, /id="branchOrdersManagementNavButton"/);
  assert.match(admin, /id="branchOrdersView"/);
  assert.match(admin, /id="branchOrdersManagementSaveInline"[^>]*>Bestellkonfiguration speichern/);
  assert.match(admin, /branchOrdersManagementNavButton[^>]*data-view="branchOrders"/);
  assert.doesNotMatch(admin, /branchOrdersManagementNavButton[^>]*href=/);
  assert.match(admin, /id="loanOverviewSettingsButton"/);
  assert.match(admin, /id="branchAccountPasswordButton"/);
  assert.match(admin, /id="branchAccountPasswordDialog"/);
  assert.match(adminScript, /"branch_orders:submit"/);
  assert.match(adminScript, /organization_accounts:password:manage/);
  assert.match(adminScript, /\/api\/portal\/v1\/branch-accounts\/passwords/);
  assert.match(adminScript, /isEmployee === false/);
  assert.match(adminScript, /function saveBranchOrdersManagement/);
  assert.match(adminScript, /captureBranchOrdersManagementDraft/);
  assert.match(adminScript, /branchOrdersManagementSaveInline\?\.addEventListener\("click", saveBranchOrdersManagement\)/);
  assert.match(adminScript, /\[elements\.branchOrdersManagementSave, elements\.branchOrdersManagementSaveInline\]/);
  assert.match(adminStyles, /branch-orders-management-toolbar/);
  assert.match(adminStyles, /grid-template-columns:minmax\(240px,\.7fr\) 1fr auto/);
  assert.match(styles, /branch-organization-account/);
  assert.match(styles, /body\.branch-organization-account \.portal-header \{ position:fixed/);
  assert.match(styles, /body\.branch-organization-account main \{ width:auto; min-height:100vh; margin:0 0 0 230px/);
});
