"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("v0.91 UI: Filialbestellung trennt Erfassung und Filialleitungs-Konfiguration", () => {
  const html = read("public/portal.html");
  const script = read("public/portal.js");
  const styles = read("public/portal.css");
  const admin = read("public/index.html");
  const adminScript = read("public/app.js");
  const adminStyles = read("public/styles.css");

  assert.match(html, /id="branchOrdersTab"/);
  assert.match(html, /id="branchOrdersView"/);
  assert.match(html, /id="branchVacationTab"/);
  assert.match(html, /id="branchVacationView"/);
  assert.match(html, /id="branchOrderEmployee"/);
  assert.match(html, /id="branchOrderSettingsCard"/);
    assert.match(html, /id="branchPortalDisplaySettingsCard"/);
    assert.match(html, /id="mobileHomeView"/);
    assert.match(html, /id="mobileHomeTiles"/);
  assert.match(html, /id="branchMobileActionBar"/);
  assert.match(html, /id="branchOrderReview"/);
  assert.match(html, /id="portalSettingsShortcut"[^>]*aria-label="Einstellungen öffnen"/);
  assert.match(html, /id="branchOrderHistoryList"/);
  assert.match(html, /id="branchOrderPortalHistoryList"/);
  assert.match(html, /id="branchOrderPortalHistoryRefresh"/);
  assert.match(html, /id="branchOrderSaveDraft"[^>]*>Entwurf speichern/);
  assert.match(html, /id="branchOrderContinueDraft"[^>]*>Fortsetzen/);
  assert.match(html, /id="branchOrderDiscardDraft"[^>]*>Verwerfen/);
  assert.match(html, /id="passwordSettingsCard"/);
  assert.doesNotMatch(html, /branchPasswordShortcut/);
  assert.match(script, /function branchOrderCapabilityEnabled/);
  assert.match(script, /function branchPortalDisplaySettingsEnabled/);
  assert.match(script, /function branchVacationCapabilityEnabled/);
  assert.match(script, /\/api\/portal\/v1\/branch-orders\/catalog/);
  assert.match(script, /\/api\/portal\/v1\/location-dashboard\/vacations/);
  assert.doesNotMatch(script, /catalog\.senderEmail/);
  assert.match(script, /\/api\/portal\/v1\/branch-orders\/settings/);
  assert.match(script, /\/api\/portal\/v1\/branch-orders\/history/);
  assert.match(script, /\/api\/portal\/v1\/branch-orders\/draft/);
  assert.match(script, /\/api\/portal\/v1\/branch-portal-settings/);
  assert.match(script, /expectedRevision: portalState\.branchOrderDraftRevision/);
  assert.match(script, /draftRevision: portalState\.branchOrderDraftRevision/);
  assert.match(script, /\/api\/portal\/v1\/branch-orders\/\$\{encodeURIComponent\(id\)\}\/pdf/);
  assert.match(script, /step="1" inputmode="numeric"/);
  assert.match(script, /function captureBranchOrderSettingsDraft/);
  assert.match(script, /function branchOrderSelection/);
  assert.match(script, /function configureBranchOrderAutosave/);
  assert.match(script, /function renderBranchOrderReview/);
    assert.match(script, /function renderBranchMobileActionBar/);
    assert.match(script, /function renderMobileHome/);
    assert.match(script, /portalState\.activeTab === "settings" \? "home" : "settings"/);
    assert.match(script, /if \(isOrganizationAccount\(user\) \|\| user\?\.isEmployee === false \|\| isMobileUi\(\)\) return false/);
  assert.match(script, /branchOrderSubmitting/);
  assert.match(script, /branch-order-group-toggle/);
  assert.match(script, /branchOrderSelection\(\)\.set/);
  assert.match(script, /passwordSettingsCard.*isOrganizationAccount/s);
  assert.match(script, /loanOverviewColumnCatalog/);
  assert.match(script, /borrowerName/);
  assert.match(admin, /id="organizationAccountBranchOrders"/);
  assert.match(admin, /id="branchOrdersManagementNavButton"/);
  assert.match(admin, /id="branchOrdersView"/);
  assert.doesNotMatch(admin, /PL\+ · Standort &amp; Übergabe/);
  assert.match(admin, /id="branchOrdersManagementSaveInline"[^>]*>Bestellkonfiguration speichern/);
  assert.match(admin, /branchOrdersManagementNavButton[^>]*data-view="branchOrders"/);
  assert.doesNotMatch(admin, /branchOrdersManagementNavButton[^>]*href=/);
  assert.match(admin, /id="loanOverviewSettingsButton"/);
  assert.match(admin, /id="branchAccountPasswordButton"/);
  assert.match(admin, /id="branchAccountPasswordDialog"/);
  assert.match(adminScript, /"branch_orders:submit"/);
  assert.match(adminScript, /organization_accounts:password:manage/);
  assert.match(adminScript, /\/api\/portal\/v1\/branch-accounts\/passwords/);
  assert.match(adminScript, /isEmployee === false/);
  assert.match(adminScript, /function saveBranchOrdersManagement/);
  assert.match(adminScript, /function moveBranchOrdersManagementEntry/);
  assert.match(adminScript, /branch-orders-management-catalog-table/);
  assert.match(adminScript, /branch-orders-management-group-table/);
  assert.match(adminScript, /branch-orders-management-group-toolbar/);
  assert.match(adminScript, /branch-orders-management-order-button/);
  assert.match(adminScript, /data-branch-orders-management-new-item-title/);
  assert.match(adminScript, /data-branch-orders-management-action="edit-catalog-item"/);
  assert.match(adminScript, /data-branch-orders-management-action="sort-catalog"/);
  assert.match(adminScript, />Bearbeiten<\/button>/);
  assert.match(adminScript, />Löschen<\/button>/);
  assert.match(adminScript, /branch-orders-management-chevron/);
  assert.match(adminScript, /\{\{employeeNickname\}\}/);
  assert.match(adminScript, /function confirmBranchOrderDelivery/);
  assert.match(adminScript, /\/delivery-confirmation/);
  assert.match(adminScript, /Zustellung technisch nicht bestätigt/);
  assert.match(adminScript, /add-catalog-item/);
  assert.match(adminScript, /move-group-item/);
  assert.match(adminScript, /add-unit/);
  assert.match(adminScript, /\["hr", "admin", "developer"\]\.includes\(state\.portalSession\?\.user\?\.role\)/);
  assert.doesNotMatch(adminScript, /\["hr", "admin", "it_admin", "developer"\]\.includes\(state\.portalSession\?\.user\?\.role\)/);
  assert.match(adminScript, /branch-orders-management-history-actions/);
  assert.match(adminScript, /captureBranchOrdersManagementDraft/);
  assert.match(adminScript, /branchOrdersManagementSaveInline\?\.addEventListener\("click", saveBranchOrdersManagement\)/);
  assert.match(adminScript, /\[elements\.branchOrdersManagementSave, elements\.branchOrdersManagementSaveInline\]/);
  assert.match(adminStyles, /branch-orders-management-toolbar/);
  assert.match(adminStyles, /branch-orders-management-history-actions/);
  assert.match(adminStyles, /branch-orders-management-catalog-table-wrap/);
  assert.match(adminStyles, /branch-orders-management-group-table-wrap/);
  assert.match(adminStyles, /branch-orders-management-group-fields/);
  assert.match(adminStyles, /branch-orders-management-table-action[^}]*text-decoration:underline/);
  assert.match(adminStyles, /branch-orders-management-catalog-create[^}]*grid-template-columns:minmax\(0,1fr\) auto/);
  assert.match(adminStyles, /branch-orders-management-workspace \{ display:grid; grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(adminStyles, /details\[open\] > summary > \.branch-orders-management-chevron \{ transform:rotate\(90deg\)/);
  assert.match(adminStyles, /branch-orders-management-sort-actions/);
  assert.match(adminStyles, /grid-template-columns:minmax\(240px,\.7fr\) 1fr auto/);
  assert.match(styles, /branch-organization-account/);
  assert.match(styles, /body\.branch-organization-account \.portal-header \{ position:fixed/);
  assert.match(styles, /body\.branch-organization-account main \{ width:auto; min-height:100vh; margin:0 0 0 230px/);
  assert.match(styles, /branch-order-history-actions/);
  assert.match(styles, /branch-order-item-select input \{ order:2/);
  assert.match(styles, /branch-order-draft-panel/);
    assert.match(styles, /body\.branch-mobile-account \.portal-tabs/);
    assert.match(styles, /portal-tabs\.mobile-settings-hidden/);
    assert.match(styles, /branch-mobile-action-active/);
    assert.match(styles, /branch-mobile-action-bar/);
    assert.match(styles, /shift-card-colored/);
    assert.match(styles, /color-mix\(in srgb,var\(--schedule-person-color\) 38%,#fff\)/);
  assert.match(styles, /branch-order-group-toggle/);
  assert.match(styles, /grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
});
