'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const S=require('../core/sql');
const {identifier,trigger}=require('../core/schema');
const {source,stageTables,relation,qualify,SEARCH_PATH}=require('./layout');
const q=value=>'"'+identifier(value).replace(/"/g,'""')+'"';
function createSalesSchemaPlan(stage=5){
  const available=new Set(stageTables(stage).map(t=>t.name));
  const prior=new Set(stage===5?[]:stageTables(stage-1).map(t=>t.name));
  const selected=stageTables(stage).filter(t=>!prior.has(t.name)),owned=new Set(selected.map(t=>t.name));
  const statements=[],indexes=[],foreign=[];
  if(stage===5){
    statements.push({id:'sales.pgcrypto',sql:'CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA gp'});
    statements.push({id:'sales.compatibility',sql:fs.readFileSync(path.join(__dirname,'../core/compatibility.sql'),'utf8')});
  }
  for(const schema of new Set(selected.map(t=>t.schema))){
    statements.push({id:'schema.'+schema,sql:`CREATE SCHEMA IF NOT EXISTS ${schema} AUTHORIZATION gp_sales_owner;GRANT USAGE ON SCHEMA ${schema} TO gp_sales_app,gp_sales_reader;ALTER DEFAULT PRIVILEGES FOR ROLE gp_sales_owner IN SCHEMA ${schema} GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO gp_sales_app;ALTER DEFAULT PRIVILEGES FOR ROLE gp_sales_owner IN SCHEMA ${schema} GRANT SELECT ON TABLES TO gp_sales_reader;ALTER DEFAULT PRIVILEGES FOR ROLE gp_sales_owner IN SCHEMA ${schema} GRANT USAGE,SELECT ON SEQUENCES TO gp_sales_app;`});
  }
  if(stage===6){
    statements.push({id:'sales.binary-type',sql:"CREATE FUNCTION gp.sqlite_typeof(value bytea) RETURNS text LANGUAGE sql IMMUTABLE AS 'SELECT CASE WHEN value IS NULL THEN ''null'' ELSE ''blob'' END'"});
    statements.push({id:'boundary.audit-outbox',sql:`CREATE TABLE integration.core_audit_outbox(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id text NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,actor text NOT NULL,action text NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,detail text NOT NULL,created_at text NOT NULL);REVOKE UPDATE,DELETE ON integration.core_audit_outbox FROM gp_sales_app;`});
  }
  if(stage===7){
    statements.push({id:'boundary.mapping-ownership',sql:`DO $guard$ BEGIN IF EXISTS(SELECT 1 FROM trade.import_master_bindings UNION ALL SELECT 1 FROM trade.import_master_holds UNION ALL SELECT 1 FROM trade.import_master_events) THEN RAISE EXCEPTION 'Block 7 requires empty development mapping stores; historical transfer belongs to block 9';END IF;END $guard$;REVOKE ALL ON trade.import_master_bindings,trade.import_master_events,trade.import_master_holds FROM gp_sales_app,gp_sales_reader;`});
    statements.push({id:'boundary.audit-delivery',sql:`CREATE TABLE integration.core_audit_delivery(event_id text PRIMARY KEY REFERENCES integration.core_audit_outbox(event_id),core_audit_id bigint NOT NULL,source_sha256 text NOT NULL CHECK(length(source_sha256)=64),delivered_at timestamptz NOT NULL DEFAULT now());REVOKE UPDATE,DELETE ON integration.core_audit_delivery FROM gp_sales_app;`});
  }
  if(stage===8){
    statements.push({id:'reporting.location-references',sql:'CREATE TABLE integration.core_location_references(id text PRIMARY KEY,source_sha256 text NOT NULL CHECK(length(source_sha256)=64));REVOKE UPDATE,DELETE ON integration.core_location_references FROM gp_sales_app;'});
    statements.push({id:'search.trigram-extension',sql:'CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA gp'});
    statements.push({id:'search.article-folded',sql:'ALTER TABLE trade.sales_article_search_projection ADD COLUMN search_text_folded TEXT COLLATE "C" GENERATED ALWAYS AS (gp.ascii_fold(gp.lower(search_text))) STORED'});
    statements.push({id:'search.article-trigram',sql:'CREATE INDEX sales_article_search_trigram ON trade.sales_article_search_projection USING gin (search_text_folded gp.gin_trgm_ops)'});
    statements.push({id:'search.article-order',sql:'CREATE INDEX sales_article_search_number ON trade.sales_article_search_projection (article_number_sort ASC NULLS FIRST,product_id ASC NULLS FIRST)'});
    for(const column of ['retail_gross','internet_gross','retail_net','internet_net','purchase_net','purchase_gross'])statements.push({id:'search.exact-price.'+column,sql:'ALTER TABLE trade.sales_article_search_projection ALTER COLUMN '+column+' TYPE NUMERIC(30,12) USING '+column+'::numeric(30,12)'});
  }
  for(const table of source.tables.filter(t=>owned.has(t.name))){
    const object=source.objects.find(o=>o.type==='table'&&o.name===table.name);
    const t=S.tokens(object.sql),start=t.indexOf('('),end=S.matching(t,start);
    const originalFields=S.split(t.slice(start+1,end));
    const fields=originalFields.map(field=>[...field]).flatMap(field=>{
      if(field[0].toUpperCase()==='FOREIGN')return [];
      const column=table.columns.find(c=>c.name===S.name(field[0]));
      if(column){
        const ref=field.findIndex(v=>v.toUpperCase()==='REFERENCES');
        if(ref>=0){let last=ref+2;if(field[last]==='(')last=S.matching(field,last)+1;while(last<field.length&&['ON','UPDATE','DELETE','CASCADE','RESTRICT','NO','ACTION','SET','NULL','DEFAULT','DEFERRABLE','INITIALLY','DEFERRED','IMMEDIATE'].includes(field[last].toUpperCase()))last++;field.splice(ref,last-ref);}
        if(column.type==='INTEGER'||column.type==='BOOLEAN'){
          field[1]=column.pk&&table.columns.filter(c=>c.pk).length===1?'BIGINT GENERATED BY DEFAULT AS IDENTITY':'BIGINT';
          field=field.filter(v=>v.toUpperCase()!=='AUTOINCREMENT');
          if(column.type==='BOOLEAN')field=field.map(v=>v.toUpperCase()==='TRUE'?'1':v.toUpperCase()==='FALSE'?'0':v);
        }else if(column.type==='REAL')field[1]='DOUBLE PRECISION';
        else if(column.type==='BLOB')field[1]='BYTEA';
        else if(column.type==='TEXT')field[1]=table.name==='sales_article_price_snapshots'&&column.name==='amount'?'NUMERIC(30,12)':'TEXT COLLATE "C"';
        else throw new Error('Unreviewed Sales column type '+table.name+'.'+column.name);
      }
      if(table.name==='sales_article_price_snapshots')field=field.map((v,i)=>S.name(v)==='amount'&&(!column||i!==0)?'(amount::text)':v);
      return [qualify(S.expression(field))];
    });
    statements.push({id:table.name,sql:`CREATE TABLE ${relation(table.name)} (${fields.join(',\n')})`});
    for(const id of new Set(table.foreignKeys.map(f=>f.id))){
      const keys=table.foreignKeys.filter(f=>f.id===id).sort((a,b)=>a.seq-b.seq),f=keys[0];
      if(!available.has(f.table)&&!(stage===8&&f.table==='locations'))throw new Error('Sales dependency needs an earlier migration '+f.table);
      const declaration=originalFields.find(field=>field[0].toUpperCase()==='FOREIGN'&&S.name(field[field.findIndex(v=>v.toUpperCase()==='REFERENCES')+1])===f.table&&S.split(field.slice(field.indexOf('(')+1,S.matching(field,field.indexOf('(')))).map(a=>S.name(a[0])).join(',')===keys.map(k=>k.from).join(','));
      const deferred=declaration?.some(v=>v.toUpperCase()==='DEFERRABLE')?' DEFERRABLE INITIALLY DEFERRED':'';
      foreign.push({id:table.name+':fk:'+id,sql:`ALTER TABLE ${relation(table.name)} ADD CONSTRAINT ${q('fk_'+table.name+'_'+id)} FOREIGN KEY (${keys.map(k=>q(k.from)).join(',')}) REFERENCES ${f.table==='locations'?'integration.core_location_references':relation(f.table)} (${keys.map(k=>q(k.to)).join(',')}) ON UPDATE ${f.on_update} ON DELETE ${f.on_delete}${deferred}`});
    }
  }
  for(const object of source.objects.filter(o=>o.type==='index'&&owned.has(o.table_name))){
    indexes.push({id:object.name,sql:qualify(S.expression(object.sql).replace(/^(CREATE (?:UNIQUE )?INDEX) \S+/i,'$1 '+q(object.name)))});
  }
  statements.push(...indexes,...foreign);
  for(const object of source.objects.filter(o=>o.type==='trigger'&&owned.has(o.table_name))){
    for(const item of trigger(object))statements.push({...item,sql:qualify(item.sql).replace(/SET search_path = pg_catalog , gp/,'SET search_path = '+SEARCH_PATH),...(item.validation?{validation:{...item.validation,condition:item.validation.condition&&qualify(item.validation.condition),actions:qualify(item.validation.actions)}}:{})});
  }
  statements.push({id:'sales.function-grants',sql:'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA gp TO gp_sales_app,gp_sales_reader'});
  return {stage,sourceSchemaSha256:source.schemaSha256,digest:crypto.createHash('sha256').update(JSON.stringify(statements)).digest('hex'),statements,sourceCounts:{tables:owned.size,indexes:indexes.length,triggers:source.objects.filter(o=>o.type==='trigger'&&owned.has(o.table_name)).length},productActivation:false};
}
module.exports={createSalesSchemaPlan};
