'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const source=require('../contracts/source-schema-v09237.json');
const inventory=require('../contracts/block-1-inventory.json');
const S=require('./sql');
const identifier=s=>Buffer.byteLength(s)>63?s.slice(0,50)+'_'+crypto.createHash('sha256').update(s).digest('hex').slice(0,12):s;
const q=s=>'"'+identifier(s).replace(/"/g,'""')+'"';
const relation=s=>'gp.'+q(s==='sales_article_revisions'?'article_reference_snapshots':s);
const core=new Set(inventory.tables.filter(t=>t.database==='core').map(t=>t.name));
function trigger(object){
  const t=S.tokens(object.sql),begin=t.findIndex(v=>v.toUpperCase()==='BEGIN'),on=t.findIndex(v=>v.toUpperCase()==='ON');
  if(begin<0||on<0||t.at(-1).toUpperCase()!=='END')throw new Error('Unrecognized trigger '+object.name);
  const when=t.findIndex((v,i)=>i>on&&v.toUpperCase()==='WHEN');
  const condition=when<0?null:S.expression(t.slice(when+1,begin));
  const actions=S.split(t.slice(begin+1,-1),';').map(action=>{
    let sql=S.text(action);
    let match=/^SELECT RAISE \( ABORT , ('(?:[^']|'')*') \)(?: WHERE ([\s\S]+))?$/i.exec(sql);
    if(match)return `${match[2]?'IF '+S.expression(match[2])+' THEN ':''}RAISE EXCEPTION USING MESSAGE=${match[1]},ERRCODE='23514';${match[2]?' END IF;':''}`;
    match=/^SELECT CASE WHEN ([\s\S]+) THEN RAISE \( ABORT , ('(?:[^']|'')*') \) END$/i.exec(sql);
    if(match)return `IF ${S.expression(match[1])} THEN RAISE EXCEPTION USING MESSAGE=${match[2]},ERRCODE='23514';END IF;`;
    if(/^SELECT/i.test(sql))throw new Error('Unreviewed SELECT trigger action '+object.name);
    return S.insertIgnore(sql)+';';
  }).join('\n');
  const functionName='trigger_'+crypto.createHash('sha256').update(object.name).digest('hex').slice(0,20);
  const event=S.text(t.slice(3,on));
  return [
    {id:object.name+':function',sql:`CREATE FUNCTION gp.${q(functionName)}() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,gp AS $gp_trigger$ BEGIN ${condition?'IF '+condition+' THEN':''}\n${actions}\n${condition?'END IF;':''} RETURN ${/\bDELETE\b/i.test(event)?'OLD':'NEW'}; END $gp_trigger$`,
      validation:{table:object.table_name,condition,actions}},
    {id:object.name,sql:`CREATE TRIGGER ${q(object.name)} ${event} ON ${relation(object.table_name)} FOR EACH ROW EXECUTE FUNCTION gp.${q(functionName)}()`},
  ];
}
function createSchemaPlan(){
  const statements=[],foreign=[],indexes=[];
  statements.push({id:'extensions.pgcrypto',sql:'CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA gp'});
  statements.push({id:'compatibility',sql:fs.readFileSync(path.join(__dirname,'compatibility.sql'),'utf8')});
  statements.push({id:'boundary.article-references',sql:`CREATE TABLE gp.article_reference_snapshots(product_id text NOT NULL,revision bigint NOT NULL CHECK(revision>0),source_digest text NOT NULL CHECK(length(source_digest)=64),article_number text NOT NULL,PRIMARY KEY(product_id,revision))`});
  statements.push({id:'boundary.article-references.permissions',sql:'REVOKE INSERT,UPDATE,DELETE ON gp.article_reference_snapshots FROM gp_core_app'});
  for(const table of source.tables.filter(t=>core.has(t.name))){
    const object=source.objects.find(o=>o.type==='table'&&o.name===table.name);
    const t=S.tokens(object.sql),start=t.indexOf('('),end=S.matching(t,start);
    const nocase=new Set();
    const fields=S.split(t.slice(start+1,end)).flatMap(field=>{
      if(field[0].toUpperCase()==='FOREIGN')return [];
      const column=table.columns.find(c=>c.name===S.name(field[0]));
      if(column){
        if(/\bCOLLATE NOCASE\b/i.test(S.text(field)))nocase.add(column.name);
        const ref=field.findIndex(v=>v.toUpperCase()==='REFERENCES');
        if(ref>=0){let to=ref+2;if(field[to]==='(')to=S.matching(field,to)+1;while(to<field.length&&['ON','UPDATE','DELETE','CASCADE','RESTRICT','NO','ACTION','SET','NULL','DEFAULT','DEFERRABLE','INITIALLY','DEFERRED','IMMEDIATE'].includes(field[to].toUpperCase()))to++;field.splice(ref,to-ref);}
        field=field.filter((v,i)=>!(v.toUpperCase()==='COLLATE'&&field[i+1]?.toUpperCase()==='NOCASE')&&!(v.toUpperCase()==='NOCASE'&&field[i-1]?.toUpperCase()==='COLLATE'));
        if(column.pk&&column.type==='INTEGER'&&table.columns.filter(c=>c.pk).length===1){field[1]='BIGINT GENERATED BY DEFAULT AS IDENTITY';field=field.filter(v=>v.toUpperCase()!=='AUTOINCREMENT');}
        else if(column.type==='INTEGER')field[1]='BIGINT';
        else if(column.type==='REAL')field[1]='DOUBLE PRECISION';
        else if(column.type==='BLOB')field[1]='BYTEA';
        else if(column.type==='TEXT')field[1]='TEXT COLLATE "C"';
        if(nocase.has(column.name)&&field.some(v=>v.toUpperCase()==='UNIQUE')){
          field=field.filter(v=>v.toUpperCase()!=='UNIQUE');
          indexes.push({id:table.name+':nocase:'+column.name,sql:`CREATE UNIQUE INDEX ${q('nc_'+table.name+'_'+column.name)} ON ${relation(table.name)} (gp.ascii_fold(${q(column.name)}) COLLATE "C")`});
        }
      }
      return [S.expression(field)];
    });
    statements.push({id:table.name,sql:`CREATE TABLE ${relation(table.name)} (${fields.join(',\n')})`});
    const ids=[...new Set(table.foreignKeys.map(f=>f.id))];
    for(const id of ids){
      const keys=table.foreignKeys.filter(f=>f.id===id).sort((a,b)=>a.seq-b.seq),f=keys[0];
      if(!core.has(f.table)&&f.table!=='sales_article_revisions')throw new Error('Unmapped foreign boundary '+table.name+' -> '+f.table);
      foreign.push({id:table.name+':fk:'+id,sql:`ALTER TABLE ${relation(table.name)} ADD CONSTRAINT ${q('fk_'+table.name+'_'+id)} FOREIGN KEY (${keys.map(f=>q(f.from)).join(',')}) REFERENCES ${relation(f.table)} (${keys.map(f=>q(f.to)).join(',')}) ON UPDATE ${f.on_update} ON DELETE ${f.on_delete}`});
    }
  }
  for(const object of source.objects.filter(o=>o.type==='index'&&core.has(o.table_name))){
    indexes.push({id:object.name,sql:S.expression(object.sql).replace(/^(CREATE (?:UNIQUE )?INDEX) \S+/i,'$1 '+q(object.name)).replace(/\bON\s+("?[\w]+"?)/i,(_,n)=>'ON '+relation(S.name(n)))});
  }
  statements.push(...indexes,...foreign);
  // The mobile notification cursor is the original SQLite insertion identity.
  // Block 9 must import historical rowids explicitly and advance this sequence.
  statements.push({id:'compatibility.notification-cursor',sql:'ALTER TABLE gp.portal_notifications ADD COLUMN rowid bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE'});
  statements.push({id:'compatibility.source-catalog',sql:"CREATE VIEW gp.source_catalog AS SELECT 'table'::text AS type,tablename::text AS name,tablename::text AS tbl_name,NULL::text AS sql FROM pg_catalog.pg_tables WHERE schemaname='gp' AND tablename IN ("+[...core].map(name=>"'"+name+"'").join(',')+")"});
  for(const object of source.objects.filter(o=>o.type==='view'))statements.push({id:object.name,sql:S.expression(object.sql).replace(/^CREATE VIEW \S+/i,'CREATE VIEW '+relation(object.name))});
  for(const object of source.objects.filter(o=>o.type==='trigger'&&core.has(o.table_name)))statements.push(...trigger(object));
  statements.push({id:'permissions.functions',sql:'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA gp TO gp_core_app,gp_core_reader'});
  const digest=crypto.createHash('sha256').update(JSON.stringify(statements)).digest('hex');
  return {version:1,profile:'core-migration-development',sourceSchemaSha256:source.schemaSha256,digest,statements,
    productActivation:false,sourceCounts:{tables:core.size,triggers:source.objects.filter(o=>o.type==='trigger'&&core.has(o.table_name)).length}};
}
module.exports={createSchemaPlan,identifier,trigger};
